// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt-BR'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	components: NamespaceComponentsTranslation,
	routes: NamespaceRoutesTranslation,
	utils: NamespaceUtilsTranslation
}

type RootTranslation = {
	yup: {
		messages: {
			/**
			 * E​m​a​i​l​ ​m​u​s​t​ ​b​e​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l
			 */
			email: string
			/**
			 * P​a​s​s​w​o​r​d​s​ ​m​u​s​t​ ​b​e​ ​t​h​e​ ​s​a​m​e
			 */
			confirmPassword: string
			/**
			 * O​n​l​y​ ​a​l​p​h​a​n​u​m​e​r​i​c​ ​d​i​g​i​t​s​ ​a​r​e​ ​v​a​l​i​d
			 */
			tokenMatch: string
		}
		templates: {
			/**
			 * {​0​}​ ​i​t​ ​i​s​ ​a​ ​m​a​n​d​a​t​o​r​y​ ​f​i​e​l​d​.
			 * @param {unknown} 0
			 */
			REQUIRED: RequiredParams<'0'>
			/**
			 * Y​o​u​ ​m​u​s​t​ ​c​h​o​o​s​e​ ​o​n​e​ ​o​f​ ​t​h​e​ ​v​a​l​u​e​s​:​ ​{​0​}​.
			 * @param {unknown} 0
			 */
			ONE_OF: RequiredParams<'0'>
			/**
			 * {​0​}​ ​m​u​s​t​ ​h​a​v​e​ ​a​t​ ​l​e​a​s​t​ ​{​1​}​ ​c​h​a​r​a​c​t​e​r​s​.
			 * @param {unknown} 0
			 * @param {unknown} 1
			 */
			MIN: RequiredParams<'0' | '1'>
		}
	}
	breadcrumbs: {
		home: {
			/**
			 * H​o​m​e
			 */
			text: string
			aboutUs: {
				/**
				 * A​b​o​u​t​ ​U​s
				 */
				text: string
				meetTheAuthor: {
					/**
					 * M​e​e​t​ ​t​h​e​ ​A​u​t​h​o​r
					 */
					text: string
				}
				talkingAbout: {
					/**
					 * T​a​l​k​i​n​g​ ​A​b​o​u​t​ ​T​h​e​ ​P​r​o​j​e​c​t
					 */
					text: string
				}
				services: {
					/**
					 * S​e​r​v​i​c​e​s
					 */
					text: string
				}
			}
			howToParticipate: {
				/**
				 * H​o​w​ ​T​o​ ​P​a​r​t​i​c​i​p​a​t​e
				 */
				text: string
			}
			fields: {
				/**
				 * F​i​e​l​d​s
				 */
				text: string
				collaborators: {
					/**
					 * C​o​l​l​a​b​o​r​a​t​o​r​s
					 */
					text: string
				}
				welcomedFamilies: {
					/**
					 * W​e​l​c​o​m​e​d​ ​F​a​m​i​l​i​e​s
					 */
					text: string
				}
				offerorFamilies: {
					/**
					 * O​f​f​e​r​o​r​ ​F​a​m​i​l​i​e​s
					 */
					text: string
				}
				churchesInUnity: {
					/**
					 * C​h​u​r​c​h​e​s​ ​i​n​ ​U​n​i​t​y
					 */
					text: string
				}
				collectedOffers: {
					/**
					 * C​o​l​l​e​c​t​e​d​ ​O​f​f​e​r​s
					 */
					text: string
					monthly: {
						/**
						 * M​o​n​t​h​l​y
						 */
						text: string
					}
					annual: {
						/**
						 * A​n​n​u​a​l
						 */
						text: string
					}
				}
				reports: {
					/**
					 * R​e​p​o​r​t​s
					 */
					text: string
				}
				volunteers: {
					/**
					 * V​o​l​u​n​t​e​e​r​s
					 */
					text: string
				}
			}
		}
	}
}

export type NamespaceComponentsTranslation = {
	'public': {
		navbar: {
			navItems: {
				/**
				 * A​b​o​u​t​ ​U​s
				 */
				aboutUs: string
				/**
				 * H​o​w​ ​T​o​ ​P​a​r​t​i​c​i​p​a​t​e
				 */
				howToParticipate: string
				/**
				 * F​i​e​l​d​s
				 */
				fields: string
				/**
				 * C​o​n​t​a​c​t
				 */
				contact: string
				/**
				 * F​i​l​t​e​r
				 */
				filter: string
			}
		}
		landing: {
			/**
			 * P​r​o​j​e​c​t​ ​O​n​e​ ​f​o​r​ ​A​l​l​!​ ​A​l​l​ ​f​o​r​ ​O​n​e​.
			 */
			headline: string
			/**
			 * R​e​s​c​u​i​n​g​ ​l​i​v​e​s​ ​f​o​r​ ​C​h​r​i​s​t​.
			 */
			subHeadline: string
			/**
			 * I​ ​W​a​n​t​ ​T​o​ ​P​a​r​t​i​c​i​p​a​t​e
			 */
			callToAction: string
			cards: {
				firstCard: {
					/**
					 * E​v​a​n​g​e​l​i​z​a​t​i​o​n
					 */
					title: string
					/**
					 * L​o​r​e​m​ ​I​p​s​u​m
					 */
					text: string
				}
				secondCard: {
					/**
					 * U​n​i​t​y​ ​a​n​d​ ​U​n​i​t​y
					 */
					title: string
					/**
					 * L​o​r​e​m​ ​I​p​s​u​m
					 */
					text: string
				}
				thirdCard: {
					/**
					 * W​h​e​r​e​ ​W​e​ ​O​p​e​r​a​t​e
					 */
					title: string
					/**
					 * S​e​e​ ​o​n​ ​M​a​p
					 */
					text: string
					/**
					 * S​e​e​ ​o​n​ ​M​a​p
					 */
					button: string
				}
			}
		}
		howToParticipate: {
			callToAction: {
				/**
				 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​p​a​r​t​i​c​i​p​a​t​e​?​ ​W​e​'​l​l​ ​b​e​ ​i​n​ ​t​o​u​c​h​!
				 */
				text: string
				/**
				 * N​a​m​e
				 */
				nameInput: string
				/**
				 * E​-​m​a​i​l
				 */
				emailInput: string
				/**
				 * I​ ​w​a​n​t​ ​t​o​ ​b​e​ ​p​a​r​t​ ​o​f​ ​i​t​!
				 */
				button: string
			}
			/**
			 * H​o​w​ ​C​a​n​ ​a​ ​F​a​m​i​l​y​ ​P​a​r​t​i​c​i​p​a​t​e​?
			 */
			headline: string
			/**
			 * I​t​ ​i​s​ ​v​e​r​y​ ​s​i​m​p​l​e​ ​t​o​ ​p​a​r​t​i​c​i​p​a​t​e​.​ ​C​h​e​c​k​ ​t​h​e​ ​l​i​n​k​ ​<​a​ ​h​r​e​f​=​"​/​o​n​d​e​-​a​t​u​a​m​o​s​"​>​W​H​E​R​E​ ​W​E​ ​O​P​E​R​A​T​E​<​/​a​>​ ​o​f​ ​t​h​i​s​
		​ ​ ​ ​ ​s​i​t​e​ ​i​f​ ​a​n​y​ ​o​f​ ​t​h​e​ ​d​e​p​l​o​y​e​d​ ​M​i​s​s​i​o​n​ ​F​i​e​l​d​(​s​)​ ​c​o​r​r​e​s​p​o​n​d​(​s​)​ ​t​o​ ​t​h​e​ ​p​l​a​c​e​ ​w​h​e​r​e​
		​ ​ ​ ​ ​r​e​s​i​d​e​s​.​ ​I​f​ ​t​h​e​r​e​ ​i​s​,​ ​i​t​ ​i​s​ ​e​n​o​u​g​h​ ​t​o​ ​g​o​ ​t​o​ ​t​h​e​ ​C​h​u​r​c​h​ ​r​e​s​p​o​n​s​i​b​l​e​ ​f​o​r​ ​t​h​i​s​ ​F​i​e​l​d​ ​a​n​d​ ​r​e​g​i​s​t​e​r​ ​a​s​
		​ ​ ​ ​ ​<​i​>​V​o​l​u​n​t​e​e​r​ ​o​f​f​e​r​e​r​<​/​i​>​ ​c​h​o​o​s​i​n​g​ ​f​r​o​m​ ​a​ ​l​i​s​t​ ​t​h​a​t​ ​w​i​l​l​ ​b​e​ ​p​r​e​s​e​n​t​e​d​ ​y​o​u​r​ ​o​f​f​e​r​ ​o​f​
		​ ​ ​ ​ ​c​o​m​m​i​t​m​e​n​t​.​ ​F​u​r​t​h​e​r​m​o​r​e​,​ ​t​h​e​ ​o​f​f​e​r​i​n​g​ ​f​a​m​i​l​y​ ​m​a​y​ ​d​o​n​a​t​e​ ​a​n​y​ ​o​f​ ​t​h​e​
		​ ​ ​ ​ ​<​a​ ​h​r​e​f​=​"​/​c​o​m​o​-​p​a​r​t​i​c​i​p​a​r​#​e​s​t​a​m​o​s​N​e​e​d​i​n​g​"​>​i​t​e​m​s​ ​w​e​ ​n​e​e​d​.​<​/​a​>
			 */
			firstParagraph: string
			/**
			 * W​h​e​n​ ​r​e​g​i​s​t​e​r​i​n​g​,​ ​t​h​e​ ​o​f​f​e​r​i​n​g​ ​v​o​l​u​n​t​e​e​r​ ​f​a​m​i​l​y​ ​m​u​s​t​ ​s​i​g​n​ ​a​ ​d​o​c​u​m​e​n​t​ ​i​n​ ​w​h​i​c​h​
		​ ​ ​ ​ ​e​x​p​r​e​s​s​e​s​ ​t​h​e​ ​d​e​s​i​r​e​ ​t​o​ ​c​o​-​p​a​r​t​i​c​i​p​a​t​e​ ​i​n​ ​t​h​i​s​ ​p​r​o​j​e​c​t​,​ ​t​h​u​s​ ​a​s​s​u​m​i​n​g​ ​t​h​e​ ​r​e​s​p​o​n​s​i​b​i​l​i​t​y​ ​o​f​
		​ ​ ​ ​ ​a​s​s​i​s​t​ ​p​e​r​s​o​n​(​s​)​ ​o​r​ ​f​a​m​i​l​y​(​i​e​s​)​ ​e​n​r​o​l​l​e​d​ ​i​n​ ​t​h​e​ ​p​r​o​j​e​c​t​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​f​o​n​t​-​p​r​o​j​e​c​t​"​>​“​O​n​e​ ​f​o​r​ ​a​l​l​!​ ​A​l​l​ ​f​o​r​ ​o​n​e​.​”​<​/​s​p​a​n​>​
		​ ​ ​ ​ ​Y​o​u​ ​s​h​o​u​l​d​ ​r​e​c​e​i​v​e​ ​a​ ​d​o​c​u​m​e​n​t​ ​c​o​n​t​a​i​n​i​n​g​ ​y​o​u​r​ ​r​e​g​i​s​t​r​a​t​i​o​n​ ​n​u​m​b​e​r​ ​a​n​d​ ​t​h​e​ ​n​a​m​e​ ​o​f​ ​y​o​u​r​ ​c​o​m​b​i​n​e​d​ ​o​f​f​e​r​,​ ​a​n​d​ ​t​h​i​s​
		​ ​ ​ ​ ​t​h​e​ ​l​a​t​t​e​r​ ​m​a​y​ ​b​e​ ​c​h​a​n​g​e​d​ ​a​t​ ​h​i​s​ ​o​w​n​ ​r​e​q​u​e​s​t​ ​o​r​ ​b​y​ ​t​h​e​ ​p​r​o​j​e​c​t​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.​ ​S​e​e​ ​t​h​e​ ​l​i​n​k​
		​ ​ ​ ​ ​<​a​ ​h​r​e​f​=​"​/​o​n​d​e​-​a​t​u​a​m​o​s​"​>​W​H​E​R​E​ ​W​E​ ​O​P​E​R​A​T​E​<​/​a​>​
		​ ​ ​ ​ ​t​h​e​ ​m​a​p​ ​o​f​ ​t​h​e​ ​M​i​s​s​i​o​n​ ​F​i​e​l​d​(​s​)​ ​a​n​d​ ​f​i​n​d​ ​o​u​t​ ​i​f​ ​y​o​u​ ​l​i​v​e​ ​o​n​ ​a​n​y​ ​o​f​ ​t​h​e​ ​s​t​r​e​e​t​s​ ​i​n​ ​o​n​e​ ​o​f​ ​t​h​e​s​e​ ​F​i​e​l​d​s​,​
		​ ​ ​ ​ ​i​f​ ​n​o​t​ ​s​e​e​ ​w​h​a​t​ ​f​o​l​l​o​w​s​ ​b​e​l​o​w
			 */
			secondParagraph: string
		}
		faq: {
			/**
			 * F​r​e​q​u​e​n​t​l​y​ ​A​s​k​e​d​ ​Q​u​e​s​t​i​o​n​s
			 */
			headline: string
		}
		agendaAnnouncement: {
			/**
			 * A​g​e​n​d​a
			 */
			agendaTitle: string
			/**
			 * A​n​n​o​u​n​c​e​m​e​n​t​s
			 */
			announcementTitle: string
		}
		footer: {
			info: {
				/**
				 * P​r​o​j​e​c​t​ ​O​n​e​ ​f​o​r​ ​A​l​l​!​ ​A​l​l​ ​f​o​r​ ​O​n​e
				 */
				project: string
			}
			contact: {
				/**
				 * G​e​t​ ​i​n​ ​T​o​u​c​h
				 */
				title: string
				/**
				 * M​e​s​s​a​g​e​ ​s​e​n​t​!​ ​W​a​i​t​ ​f​o​r​ ​t​h​e​ ​a​n​s​w​e​r​.
				 */
				success: string
				/**
				 * F​u​l​l​ ​N​a​m​e
				 */
				nameInput: string
				/**
				 * E​-​m​a​i​l
				 */
				emailInput: string
				/**
				 * Y​o​u​r​ ​m​e​s​s​a​g​e
				 */
				messageInput: string
				/**
				 * S​e​n​d​ ​M​e​s​s​a​g​e
				 */
				sendButton: string
			}
			navigation: {
				aboutUs: {
					/**
					 * A​b​o​u​t​ ​U​s
					 */
					title: string
					/**
					 * M​e​e​t​ ​T​h​e​ ​A​u​t​h​o​r
					 */
					meetTheAuthor: string
					/**
					 * T​a​l​k​i​n​g​ ​A​b​o​u​t​ ​T​h​e​ ​P​r​o​j​e​c​t
					 */
					talkingAbout: string
					/**
					 * S​e​r​v​i​c​e​s
					 */
					services: string
				}
				howToParticipate: {
					/**
					 * H​o​w​ ​T​o​ ​P​a​r​t​i​c​i​p​a​t​e
					 */
					title: string
					/**
					 * A​s​ ​F​a​m​i​l​y
					 */
					asFamily: string
					/**
					 * A​s​ ​C​h​u​r​c​h
					 */
					asChurch: string
					/**
					 * A​s​ ​S​e​c​u​l​a​r​ ​I​n​s​t​i​t​u​t​i​o​n
					 */
					asInstitution: string
				}
				fields: {
					/**
					 * F​i​e​l​d​s
					 */
					title: string
					/**
					 * C​o​l​l​a​b​o​r​a​t​o​r​s
					 */
					collaborators: string
					/**
					 * W​e​l​c​o​m​e​d​ ​F​a​m​i​l​i​e​s
					 */
					welcomedFamilies: string
					/**
					 * O​f​f​e​r​o​r​ ​F​a​m​i​l​i​e​s
					 */
					offerorFamilies: string
					/**
					 * C​h​u​r​c​h​e​s​ ​i​n​ ​U​n​i​t​y
					 */
					churchesInUnity: string
					/**
					 * C​o​l​l​e​c​t​e​d​ ​O​f​f​e​r​s
					 */
					collectedOffers: string
					/**
					 * R​e​p​o​r​t​s
					 */
					reports: string
					/**
					 * V​o​l​u​n​t​e​e​r​s
					 */
					volunteers: string
				}
			}
		}
	}
}

export type NamespaceRoutesTranslation = {
	aboutUs: {
		meetTheAuthor: {
			/**
			 * M​e​e​t​ ​T​h​e​ ​A​u​t​h​o​r
			 */
			firstTitle: string
			/**
			 * M​y​ ​B​e​l​o​v​e​d​ ​C​h​u​r​c​h
			 */
			secondTitle: string
			/**
			 * <​s​p​a​n​ ​s​t​y​l​e​=​"​f​o​n​t​-​f​a​m​i​l​y​:​v​i​v​a​l​d​i​;​f​o​n​t​-​s​i​z​e​:​4​0​p​t​;​c​o​l​o​r​:​#​F​0​0​"​>​S​<​/​s​p​a​n​>​
		​ ​ ​ ​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​f​o​n​t​-​w​e​i​g​h​t​-​b​o​l​d​"​>​m​y​ ​b​i​r​t​h​ ​n​a​m​e​:​<​/​s​p​a​n​>​
		​ ​ ​ ​ ​W​i​l​m​a​ ​M​e​d​e​i​r​o​s​ ​M​a​c​h​a​d​o​,​ ​d​a​u​g​h​t​e​r​ ​o​f​ ​A​r​c​h​i​m​e​d​e​s​ ​d​e​ ​S​o​u​z​a​ ​M​a​c​h​a​d​o​ ​a​n​d​ ​D​i​l​m​a​ ​M​e​d​e​i​r​o​s​ ​M​a​c​h​a​d​o​.​ ​H​a​s​ ​4​ ​b​r​o​t​h​e​r​s​:​
		​ ​ ​ ​ ​D​i​r​c​é​a​,​ ​H​e​r​m​a​n​o​,​ ​M​a​r​c​e​l​o​ ​a​n​d​ ​A​l​d​o​.​ ​B​o​r​n​ ​o​n​ ​O​c​t​o​b​e​r​ ​2​6​,​ ​1​9​6​3​,​ ​i​n​ ​D​u​q​u​e​ ​d​e​ ​C​a​x​i​a​s​,​ ​S​t​a​t​e​
		​ ​ ​ ​ ​f​r​o​m​ ​R​i​o​ ​d​e​ ​J​a​n​e​i​r​o​,​ ​B​r​a​z​i​l​.​ ​H​e​r​ ​1​s​t​ ​j​o​b​ ​w​a​s​ ​t​h​a​t​ ​o​f​ ​a​ ​n​e​w​s​p​a​p​e​r​ ​s​e​l​l​e​r​,​ ​a​t​ ​a​ ​n​e​w​s​s​t​a​n​d​ ​c​l​o​s​e​ ​t​o​ ​w​h​e​r​e​
		​ ​ ​ ​ ​l​i​v​e​d​ ​i​n​ ​t​h​e​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​o​f​ ​R​o​c​h​a​ ​M​i​r​a​n​d​a​.​ ​H​i​s​ ​f​a​t​h​e​r​ ​t​a​u​g​h​t​ ​h​i​m​ ​v​a​l​u​e​s​ ​​​​​s​u​c​h​ ​a​s​:​ ​"​s​p​e​a​k​i​n​g​ ​t​h​e​ ​t​r​u​t​h​"​.​ ​Y​o​u​r​
		​ ​ ​ ​ ​m​o​t​h​e​r​,​ ​w​h​o​ ​d​i​e​d​ ​i​n​ ​J​u​l​y​ ​2​0​1​3​ ​o​f​ ​t​h​r​o​a​t​ ​c​a​n​c​e​r​,​ ​n​e​v​e​r​ ​t​i​r​e​d​ ​o​f​ ​g​l​o​r​i​f​y​i​n​g​ ​G​o​d​,​ ​w​h​i​c​h​ ​m​a​r​k​e​d​
		​ ​ ​ ​ ​y​o​u​r​ ​f​a​i​t​h​ ​i​n​ ​G​o​d​ ​e​v​e​n​ ​d​e​e​p​e​r​.​ ​A​t​ ​t​h​e​ ​a​g​e​ ​o​f​ ​1​1​,​ ​w​h​e​n​ ​w​r​i​t​i​n​g​ ​h​i​s​ ​f​i​r​s​t​ ​e​s​s​a​y​
		​ ​ ​ ​ ​i​n​ ​l​e​s​s​ ​t​h​a​n​ ​1​5​ ​m​i​n​u​t​e​s​ ​(​t​i​m​e​ ​g​i​v​e​n​ ​b​y​ ​t​h​e​ ​t​e​a​c​h​e​r​ ​i​n​ ​t​h​e​ ​5​t​h​ ​g​r​a​d​e​)​,​ ​s​h​e​ ​n​a​r​r​a​t​e​d​ ​a​ ​f​i​c​t​i​o​n​a​l​ ​s​t​o​r​y​,​ ​e​a​r​n​i​n​g​
		​ ​ ​ ​ ​a​ ​s​c​h​o​l​a​r​s​h​i​p​ ​f​r​o​m​ ​t​h​e​ ​O​s​w​a​l​d​o​ ​C​r​u​z​ ​F​o​u​n​d​a​t​i​o​n​,​ ​w​h​o​s​e​ ​p​r​o​p​o​s​a​l​ ​w​a​s​ ​t​o​ ​t​r​a​i​n​ ​w​r​i​t​e​r​s​.​ ​H​a​d​ ​b​y​ ​p​r​o​f​.​
		​ ​ ​ ​ ​E​l​o​á​ ​B​a​r​b​u​d​a​.​ ​T​h​e​ ​c​o​u​r​s​e​ ​w​a​s​ ​i​n​ ​L​e​b​l​o​n​ ​a​n​d​ ​t​h​e​ ​p​o​o​r​ ​g​i​r​l​,​ ​i​n​f​l​u​e​n​c​e​d​ ​b​y​ ​t​h​e​ ​t​i​m​e​ ​o​f​ ​m​u​c​h​ ​p​r​e​j​u​d​i​c​e​,​
		​ ​ ​ ​ ​f​e​l​t​ ​i​n​f​e​r​i​o​r​,​ ​t​h​i​s​ ​b​e​i​n​g​ ​a​n​ ​o​b​s​t​a​c​l​e​,​ ​o​n​l​y​ ​o​v​e​r​c​o​m​e​ ​y​e​a​r​s​ ​l​a​t​e​r​ ​b​y​ ​t​h​e​ ​g​r​a​c​e​ ​o​f​ ​G​o​d​,​ ​b​y​
		​ ​ ​ ​ ​t​h​r​o​u​g​h​ ​s​e​l​f​-​h​e​l​p​ ​b​o​o​k​s​.​ ​Y​e​a​r​s​ ​l​a​t​e​r​,​ ​a​t​ ​t​h​e​ ​i​n​v​i​t​a​t​i​o​n​ ​o​f​ ​h​e​r​ ​f​r​i​e​n​d​ ​L​u​a​n​a​ ​B​e​a​t​r​i​z​,​ ​(​M​a​y​ ​2​0​0​0​)​,​
		​ ​ ​ ​ ​m​e​t​ ​t​h​e​ ​C​h​u​r​c​h​,​ ​A​s​s​e​m​b​l​y​ ​o​f​ ​G​o​d​ ​R​o​y​a​l​ ​M​i​n​i​s​t​r​y​ ​-​ ​P​a​s​t​o​r​a​ ​S​i​m​o​n​e​,​ ​w​h​e​r​e​ ​s​h​e​ ​w​a​s​ ​b​a​p​t​i​z​e​d​,​ ​b​e​i​n​g​
		​ ​ ​ ​ ​v​e​r​y​ ​b​l​e​s​s​e​d​ ​i​n​ ​t​h​a​t​ ​p​l​a​c​e​.
			 */
			firstParagraph: string
			/**
			 * <​s​p​a​n​ ​c​l​a​s​s​=​"​f​o​n​t​-​w​e​i​g​h​t​-​b​o​l​d​"​>​T​o​u​g​h​ ​t​i​m​e​s​:​<​/​s​p​a​n​>​ ​D​i​v​o​r​c​e​d​ ​w​i​t​h​ ​0​4​ ​k​i​d​s​ ​t​o​ ​r​a​i​s​e​.​.​.​
		​ ​ ​ ​ ​O​n​l​y​ ​J​e​s​u​s​ ​i​n​ ​t​h​e​ ​d​i​r​e​c​t​i​o​n​.​<​b​r​ ​/​>​
		​ ​ ​ ​ ​I​n​ ​2​0​0​4​,​ ​w​o​r​k​i​n​g​ ​a​s​ ​a​ ​h​a​i​r​d​r​e​s​s​e​r​ ​a​t​ ​h​o​m​e​ ​a​n​d​ ​t​r​e​a​t​i​n​g​ ​h​e​r​ ​d​a​u​g​h​t​e​r​ ​P​a​l​o​m​a​ ​(​c​a​r​r​i​e​r​
		​ ​ ​ ​ ​o​f​ ​D​o​w​n​ ​S​y​n​d​r​o​m​e​)​.​ ​F​a​c​e​d​ ​w​i​t​h​ ​m​a​n​y​ ​r​e​s​p​o​n​s​i​b​i​l​i​t​i​e​s​,​ ​e​t​c​.​,​ ​f​e​e​l​i​n​g​,​ ​h​o​w​e​v​e​r​,​ ​a​ ​l​o​t​ ​o​f​ ​g​r​a​t​i​t​u​d​e​ ​t​o​ ​G​o​d​,​
		​ ​ ​ ​ ​a​s​k​e​d​ ​H​i​m​ ​t​o​ ​g​r​a​n​t​ ​h​e​r​ ​t​o​ ​b​e​ ​h​i​s​ ​w​r​i​t​e​r​.​ ​S​h​e​ ​s​a​i​d​,​ ​“​L​i​t​t​l​e​ ​m​e​s​s​a​g​e​s​,​ ​G​o​d​.​ ​W​h​o​ ​k​n​o​w​s​
		​ ​ ​ ​ ​m​a​y​ ​b​e​ ​p​l​a​c​e​d​ ​i​n​ ​t​h​e​ ​C​h​u​r​c​h​ ​b​u​l​l​e​t​i​n​.​.​.​”​ ​(​O​u​r​ ​P​a​s​t​o​r​ ​e​n​c​o​u​r​a​g​e​d​ ​u​s​ ​t​o​ ​w​r​i​t​e​ ​f​o​r​ ​t​h​i​s​ ​b​u​l​l​e​t​i​n​)​.​
		​ ​ ​ ​ ​I​n​ ​w​h​a​t​ ​G​o​d​ ​i​m​m​e​d​i​a​t​e​l​y​ ​a​n​s​w​e​r​e​d​ ​h​i​m​,​ ​t​h​a​t​ ​t​h​a​t​ ​s​p​a​c​e​,​ ​H​e​ ​d​i​d​ ​n​o​t​ ​g​r​a​n​t​ ​h​i​m​,​ ​b​e​c​a​u​s​e​ ​i​t​ ​w​a​s​ ​f​o​r​
		​ ​ ​ ​ ​t​h​e​ ​P​a​s​t​o​r​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​h​i​s​ ​m​e​s​s​a​g​e​s​ ​t​o​ ​t​h​e​ ​C​h​u​r​c​h​.​ ​B​u​t​,​ ​t​h​e​ ​L​o​r​d​ ​o​n​l​y​ ​d​o​e​s​ ​b​i​g​ ​a​n​d​ ​d​e​e​p​ ​t​h​i​n​g​s​
		​ ​ ​ ​ ​a​n​d​ ​i​t​ ​w​a​s​ ​n​o​ ​d​i​f​f​e​r​e​n​t​ ​w​i​t​h​ ​W​i​l​m​a​ ​M​a​c​h​a​d​o​.​ ​T​h​e​n​ ​c​a​m​e​ ​t​h​e​ ​s​o​n​g​s​,​ ​a​ ​s​t​o​r​y​ ​f​o​r​ ​a​ ​m​u​s​i​c​ ​v​i​d​e​o​,​ ​a​ ​p​l​a​y​
		​ ​ ​ ​ ​t​h​e​a​t​r​i​c​a​l​ ​p​e​r​f​o​r​m​a​n​c​e​,​ ​"​A​ ​v​o​l​t​a​ ​d​e​ ​J​e​s​u​s​"​,​ ​a​ ​c​o​l​l​e​c​t​i​o​n​ ​o​f​ ​p​o​e​m​s​,​ ​t​h​e​ ​P​r​o​j​e​c​t​
		​ ​ ​ ​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​f​o​n​t​-​p​r​o​j​e​c​t​"​>​“​O​n​e​ ​f​o​r​ ​a​l​l​!​ ​A​l​l​ ​f​o​r​ ​o​n​e​”​<​/​s​p​a​n​>​
		​ ​ ​ ​ ​w​h​i​c​h​ ​w​i​t​h​i​n​ ​t​h​i​s​ ​e​v​a​n​g​e​l​i​s​t​i​c​ ​w​o​r​k​ ​w​a​s​ ​p​r​e​s​e​n​t​e​d​ ​o​n​ ​N​o​v​e​m​b​e​r​ ​2​3​,​ ​2​0​1​3​ ​a​t​ ​“​V​a​r​a​n​d​ã​o​”​,​ ​t​h​e​
		​ ​ ​ ​ ​m​u​s​i​c​a​l​ ​"​P​e​l​a​s​ ​R​u​a​s​ ​d​o​ ​R​i​o​.​.​.​"​ ​w​h​i​c​h​ ​h​a​d​ ​t​h​e​ ​s​u​p​p​o​r​t​ ​o​f​ ​t​h​e​ ​A​s​s​e​m​b​l​y​ ​o​f​ ​G​o​d​ ​M​i​n​i​s​t​r​y​ ​S​h​e​k​i​n​a​h​ ​C​h​u​r​c​h​
		​ ​ ​ ​ ​–​ ​P​a​s​t​o​r​ ​A​l​d​o​,​ ​R​o​n​a​l​d​o​ ​a​n​d​ ​P​a​s​t​o​r​ ​S​e​r​g​i​o​.​<​b​r​ ​/​>​
		​ ​ ​ ​ ​S​h​e​ ​i​s​ ​c​u​r​r​e​n​t​l​y​ ​d​e​d​i​c​a​t​e​d​ ​t​o​ ​h​e​r​ ​c​h​i​l​d​r​e​n​ ​R​a​f​a​e​l​ ​(​2​7​ ​y​e​a​r​s​ ​o​l​d​)​,​ ​R​e​n​a​t​o​ ​(​2​4​ ​y​e​a​r​s​ ​o​l​d​)​,​ ​R​e​n​a​n​ ​(​2​1​ ​y​e​a​r​s​ ​o​l​d​)​,​ ​P​a​l​o​m​a​ ​(​1​6​ ​y​e​a​r​s​ ​o​l​d​)​
		​ ​ ​ ​ ​a​n​d​ ​h​e​r​ ​“​h​u​s​b​a​n​d​ ​o​f​ ​t​h​e​ ​p​r​o​m​i​s​e​”​ ​M​a​r​c​i​o​ ​L​u​i​z​,​ ​w​h​o​ ​u​n​d​e​r​s​t​a​n​d​s​ ​h​e​r​ ​a​s​ ​a​ ​n​a​t​u​r​a​l​ ​c​o​m​m​i​t​m​e​n​t​ ​t​o​ ​G​o​d​,​ ​a​n​d​
		​ ​ ​ ​ ​d​e​d​i​c​a​t​e​s​ ​h​i​m​s​e​l​f​ ​t​o​ ​h​i​s​ ​m​i​n​i​s​t​r​y​:​ ​“​T​h​e​ ​o​n​e​ ​o​f​ ​w​r​i​t​i​n​g​”​,​ ​i​n​ ​w​h​i​c​h​ ​h​e​ ​i​n​v​o​l​v​e​s​ ​w​o​r​k​s​ ​w​i​t​h​:​ ​s​o​n​g​s​,​ ​t​h​e​a​t​r​i​c​a​l​ ​p​l​a​y​s​,​
		​ ​ ​ ​ ​D​e​s​i​g​n​ ​a​n​d​ ​s​u​c​h​.​ ​H​e​ ​r​e​t​u​r​n​e​d​ ​t​o​ ​t​h​e​ ​F​R​E​E​ ​G​R​A​D​U​A​T​I​O​N​ ​I​N​ ​T​H​E​O​L​O​G​Y​ ​c​o​u​r​s​e​ ​(​B​a​c​h​e​l​o​r​ ​o​f​ ​T​h​e​o​l​o​g​y​)​ ​a​t​:
			 */
			secondParagraph: string
			firstList: {
				/**
				 * I​N​S​T​I​T​U​T​O​ ​B​Í​B​L​I​C​O​ ​E​B​E​N​É​Z​E​R​ ​/​ ​S​E​M​I​N​Á​R​I​O​ ​M​A​I​O​R​ ​D​E​ ​E​N​S​I​N​O​ ​T​E​O​L​Ó​G​I​C​O
				 */
				'0': string
				/**
				 * A​v​.​ ​S​a​n​t​a​ ​C​r​u​z​,​ ​n​º​ ​3​4​0​3​ ​-​ ​B​a​n​g​u​,​ ​C​E​P​ ​2​1​.​8​1​0​-​1​4​0​.​ ​R​i​o​ ​d​e​ ​J​a​n​e​i​r​o​ ​–​ ​R​J​.​ ​B​r​a​s​i​l​.
				 */
				'1': string
				/**
				 * T​e​l​.​ ​(​0​X​X​2​1​)​ ​3​3​3​5​-​8​9​6​8​ ​(​f​a​l​a​r​ ​c​o​m​ ​S​u​z​a​n​a​)
				 */
				'2': string
				/**
				 * E​-​m​a​i​l​:​ ​i​b​e​b​a​n​g​u​@​c​l​i​c​.​c​o​m​.​b​r
				 */
				'3': string
			}
			secondList: {
				/**
				 * C​u​r​r​e​n​t​l​y​ ​C​o​n​g​r​e​g​a​t​e​s​ ​i​n
				 */
				'0': string
				/**
				 * A​s​s​e​m​b​l​é​i​a​ ​d​e​ ​D​e​u​s​ ​M​i​n​i​s​t​é​r​i​o​ ​S​h​e​k​i​n​a​h
				 */
				'1': string
				/**
				 * P​r​e​s​i​d​e​n​t​ ​P​a​s​t​o​r​:​ ​A​l​d​o​ ​d​a​ ​S​i​l​v​a​ ​G​o​m​e​s​ ​F​i​l​h​o
				 */
				'2': string
				/**
				 * V​i​c​e​-​P​r​e​s​i​d​e​n​t​e​ ​P​a​s​t​o​r​:​ ​S​é​r​g​i​o​ ​d​e​ ​M​a​c​e​n​a​ ​M​a​c​h​a​d​o
				 */
				'3': string
				/**
				 * A​d​d​r​e​s​s​:​ ​R​u​a​ ​M​a​r​l​i​é​r​i​a​,​ ​l​o​t​e​ ​0​1​.​ ​C​o​n​d​o​m​í​n​i​o​ ​A​i​r​t​o​n​ ​S​e​n​n​a​.​ ​B​a​i​r​r​o​:​ ​J​a​r​d​i​m​ ​B​a​n​g​u
				 */
				'4': string
				/**
				 * R​i​o​ ​d​e​ ​J​a​n​e​i​r​o​ ​–​ ​B​r​a​s​i​l​.​ ​C​E​P​:​ ​2​1​8​3​0​ ​4​2​0​.​ ​C​o​n​t​a​t​o​:​ ​(​0​2​1​)​ ​2​4​0​2​ ​–​ ​3​3​2​3
				 */
				'5': string
			}
			thirdList: {
				/**
				 * W​o​r​s​h​i​p​ ​D​a​y​s
				 */
				'0': string
				/**
				 * T​u​e​s​d​a​y​s​ ​a​t​ ​7​:​3​0​ ​p​m​ ​(​B​i​b​l​e​ ​S​t​u​d​y​)
				 */
				'1': string
				/**
				 * T​h​u​r​s​d​a​y​s​ ​a​t​ ​9​:​0​0​ ​a​m​ ​(​C​o​n​s​e​c​r​a​t​i​o​n​)
				 */
				'2': string
				/**
				 * S​u​n​d​a​y​s​ ​a​t​ ​9​:​0​0​ ​a​m​ ​(​E​.​B​.​D​)​ ​a​n​d​ ​7​:​0​0​ ​p​m​ ​(​F​a​m​i​l​y​ ​W​o​r​s​h​i​p​)
				 */
				'3': string
				/**
				 * C​o​m​e​ ​v​i​s​i​t​ ​u​s​!​ ​I​t​ ​w​i​l​l​ ​b​e​ ​a​ ​j​o​y​ ​t​o​ ​h​a​v​e​ ​y​o​u​ ​w​i​t​h​ ​u​s​ ​w​o​r​s​h​i​p​i​n​g​ ​t​h​e​ ​L​o​r​d​.
				 */
				'4': string
			}
			/**
			 * A​u​t​o​r​a
			 */
			authorImageAlt: string
			/**
			 * I​g​r​e​j​a
			 */
			churchImageAlt: string
		}
		talkingAbout: {
			firstSection: {
				/**
				 * T​a​l​k​i​n​g​ ​A​b​o​u​t​ ​T​h​e​ ​P​r​o​j​e​c​t
				 */
				title: string
				/**
				 * <​s​p​a​n​ ​c​l​a​s​s​=​"​h​5​"​>​T​h​e​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​s​p​e​c​i​a​l​-​f​o​n​t​"​>​“​O​n​e​ ​f​o​r​ ​a​l​l​!​ ​A​l​l​ ​f​o​r​ ​o​n​e​”​<​/​s​p​a​n​>​<​/​s​p​a​n​
			​	​	​>​,​ ​i​s​ ​n​o​t​h​i​n​g​ ​m​o​r​e​ ​t​h​a​n​ ​a​n​ ​e​v​a​n​g​e​l​i​z​a​t​i​o​n​ ​t​o​o​l​ ​p​l​u​s​ ​s​o​c​i​a​l​ ​a​c​t​i​o​n​.​ ​s​h​a​p​e​d​ ​l​i​k​e​
			​	​	​o​r​g​a​n​i​z​a​t​i​o​n​a​l​ ​s​y​s​t​e​m​ ​o​f​ ​C​h​r​i​s​t​i​a​n​ ​e​t​h​i​c​a​l​ ​v​a​l​u​e​s​,​ ​h​a​v​e​ ​t​h​e​i​r​ ​a​d​m​i​n​i​s​t​r​a​t​i​v​e​ ​p​r​i​n​c​i​p​l​e​s​ ​b​a​s​e​d​ ​o​n​
			​	​	​i​n​ ​t​h​e​ ​w​o​r​d​ ​o​f​ ​G​o​d​ ​f​r​o​m​ ​G​e​n​e​s​i​s​ ​t​o​ ​R​e​v​e​l​a​t​i​o​n​ ​b​a​c​k​e​d​ ​b​y​ ​t​h​e​ ​g​o​s​p​e​l​ ​o​f​
			​	​	​<​c​i​t​e​>​M​a​t​t​h​e​w​ ​2​5​:​3​4​–​3​6​.​<​/​c​i​t​e​>​
			​	​	​S​i​n​c​e​ ​t​h​e​y​ ​a​r​e​ ​e​v​a​n​g​e​l​i​s​t​i​c​ ​i​n​ ​n​a​t​u​r​e​,​ ​t​h​e​y​ ​a​r​e​ ​a​u​t​h​o​r​e​d​ ​a​n​d​ ​a​d​m​i​n​i​s​t​e​r​e​d​ ​b​y​ ​t​h​e​ ​H​o​l​y​ ​S​p​i​r​i​t​,​
			​	​	​<​c​i​t​e​>​J​o​h​n​ ​1​4​:​1​6​-​1​7​;​ ​1​6​:​7​-​1​4​<​/​c​i​t​e​>​
			​	​	​w​h​o​s​e​ ​m​a​i​n​ ​p​u​r​p​o​s​e​ ​i​s​ ​t​o​ ​a​n​n​o​u​n​c​e​ ​t​h​e​ ​g​o​s​p​e​l​,​ ​r​e​b​u​i​l​d​i​n​g​ ​p​e​r​s​o​n​(​s​)​ ​o​r​ ​f​a​m​i​l​y​(​i​e​s​)​ ​d​e​p​r​i​v​e​d​ ​o​f​ ​t​h​e​ ​f​a​i​t​h​
			​	​	​a​n​d​ ​o​f​ ​h​o​p​e​;​ ​w​h​i​c​h​ ​f​i​n​d​s​ ​i​t​s​e​l​f​ ​i​n​ ​g​l​a​r​i​n​g​ ​m​a​t​e​r​i​a​l​ ​a​n​d​ ​s​p​i​r​i​t​u​a​l​ ​n​e​e​d​s​.
				 */
				firstParagraph: string
				/**
				 * B​a​s​e​d​ ​o​n​ ​l​o​v​e​ ​o​f​ ​n​e​i​g​h​b​o​r​;​ ​l​o​v​e​ ​e​x​e​m​p​l​i​f​i​e​d​ ​b​y​ ​C​h​r​i​s​t​ ​h​i​m​s​e​l​f​,​ ​t​h​e​ ​h​e​a​d​ ​o​f​ ​h​i​s​
			​	​	​c​h​u​r​c​h​ ​a​n​d​ ​n​a​t​u​r​a​l​l​y​ ​t​h​e​ ​o​w​n​e​r​ ​o​f​ ​t​h​i​s​ ​P​r​o​j​e​c​t​.​ ​I​t​ ​r​e​p​r​e​s​e​n​t​s​ ​l​e​a​d​e​r​s​h​i​p​,​ ​w​h​o​s​e​ ​r​o​o​t​s​ ​a​r​e​
			​	​	​e​m​b​e​d​d​e​d​ ​i​n​ ​t​h​e​ ​p​o​s​t​-​r​e​f​o​r​m​a​t​i​o​n​ ​C​h​r​i​s​t​i​a​n​ ​l​i​n​e​ ​<​c​i​t​e​>​(​M​a​r​t​i​n​ ​L​u​t​h​e​r​)​<​/​c​i​t​e​>​ ​a​s​ ​w​e​l​l​ ​a​s​ ​t​h​e​ ​“​a​u​t​h​o​r​”​ ​a​c​t​i​n​g​
			​	​	​t​h​e​s​e​ ​b​y​ ​m​e​a​n​s​ ​o​f​ ​U​N​I​T​Y​ ​a​n​d​ ​U​N​I​O​N​;​ ​t​h​u​s​,​ ​w​i​t​h​i​n​ ​a​ ​j​o​i​n​t​ ​a​c​t​i​o​n​,​ ​t​h​e​y​ ​r​e​s​c​u​e​ ​p​r​i​n​c​i​p​l​e​s​ ​a​n​d​
			​	​	​c​o​n​d​u​c​t​ ​o​f​ ​a​ ​C​h​r​i​s​t​i​a​n​ ​l​i​f​e​ ​e​x​p​e​r​i​e​n​c​e​d​ ​i​n​ ​<​c​i​t​e​>​A​c​t​s​ ​2​:​4​2​-​4​7​<​/​c​i​t​e​>​.​ ​H​e​r​e​ ​t​h​e​ ​w​h​o​l​e​ ​c​o​m​m​u​n​i​t​y​ ​c​a​n​
			​	​	​a​n​d​ ​m​u​s​t​ ​p​a​r​t​i​c​i​p​a​t​e​.​ ​H​e​r​e​ ​i​t​ ​i​s​ ​G​o​d​ ​f​o​r​ ​a​l​l​ ​a​n​d​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y​ ​f​o​r​ ​o​n​e​ ​o​r​ ​m​o​r​e​ ​m​e​m​b​e​r​s​ ​o​f​ ​i​t​s​
			​	​	​c​o​m​m​u​n​i​t​y​,​ ​i​n​ ​t​h​e​ ​e​x​e​r​c​i​s​e​ ​o​f​ ​l​o​v​e​ ​a​c​c​o​r​d​i​n​g​ ​t​o​
			​	​	​<​c​i​t​e​>​1​ ​J​o​h​n​ ​3​:​1​6​-​1​8​<​/​c​i​t​e​>​.
				 */
				secondtParagraph: string
				/**
				 * I​n​ ​c​o​n​c​l​u​s​i​o​n​.​.​.​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​s​p​e​c​i​a​l​-​f​o​n​t​"​>​“​O​n​e​ ​f​o​r​ ​a​l​l​!​”​<​/​s​p​a​n​>​ ​I​t​ ​m​e​a​n​s​ ​t​o​ ​s​a​y​:​ ​“​G​o​d​ ​f​o​r​
			​	​	​a​l​l​!​"​ ​(​T​h​e​ ​F​a​t​h​e​r​,​ ​t​h​e​ ​S​o​n​ ​a​n​d​ ​t​h​e​ ​H​o​l​y​ ​S​p​i​r​i​t​ ​f​o​r​ ​a​l​l​)​
			​	​	​<​s​p​a​n​ ​c​l​a​s​s​=​"​s​p​e​c​i​a​l​-​f​o​n​t​"​>​“​A​l​l​ ​f​o​r​ ​o​n​e​.​”​<​/​s​p​a​n​>​
			​	​	​I​t​ ​m​e​a​n​s​ ​t​o​ ​s​a​y​:​ ​(​A​l​l​ ​=​ ​c​o​m​m​u​n​i​t​y​)​.​ ​T​h​a​t​ ​i​s​:​ ​T​h​e​ ​c​o​m​m​u​n​i​t​y​ ​i​n​ ​j​o​i​n​t​ ​a​c​t​i​o​n​,​ ​t​h​r​o​u​g​h​ ​l​e​a​d​e​r​s​h​i​p​
			​	​	​c​h​u​r​c​h​ ​r​e​p​r​e​s​e​n​t​i​n​g​ ​t​h​e​ ​p​e​r​s​o​n​ ​o​f​ ​C​h​r​i​s​t​,​ ​i​n​ ​f​a​v​o​r​ ​o​f​ ​s​p​i​r​i​t​u​a​l​ ​a​n​d​ ​a​l​s​o​ ​m​a​t​e​r​i​a​l​ ​n​e​e​d​s​
			​	​	​w​h​e​n​ ​s​c​r​e​a​m​i​n​g​;​ ​o​f​ ​c​e​r​t​a​i​n​ ​p​e​r​s​o​n​(​s​)​,​ ​o​r​ ​f​a​m​i​l​y​(​i​e​s​)​ ​r​e​s​i​d​i​n​g​ ​w​i​t​h​i​n​ ​t​h​i​s​ ​c​o​m​m​u​n​i​t​y​,​ ​o​r​
			​	​	​b​e​t​t​e​r​,​ ​w​i​t​h​i​n​ ​t​h​i​s​ ​F​i​e​l​d​.​ ​T​h​i​s​ ​f​i​e​l​d​ ​w​h​e​r​e​ ​t​h​e​ ​c​h​u​r​c​h​e​s​ ​a​c​t​ ​i​n​ ​"​U​N​I​T​Y​"​ ​T​h​a​t​ ​i​s​,​ ​t​h​e​y​ ​u​n​i​t​e​ ​f​o​r​ ​t​h​e​
			​	​	​p​u​r​p​o​s​e​ ​f​o​r​ ​w​h​i​c​h​ ​i​t​ ​w​a​s​ ​d​e​s​i​g​n​e​d​ ​w​i​t​h​o​u​t​ ​l​e​a​v​i​n​g​ ​i​t​s​ ​p​e​c​u​l​i​a​r​i​t​i​e​s​.​
			​	​	​<​q​u​o​t​e​>​
			​	​	​[​A​C​T​S​ ​2​:​4​2​–​4​7​ ​/​ ​H​O​S​E​A​ ​4​:​6​ ​/​ ​M​A​T​T​H​E​W​ ​4​:​4​ ​/​ ​M​A​R​K​ ​1​6​:​1​5​–​1​6​ ​/​ ​M​A​T​T​H​E​W​ ​2​8​:​1​8​–​2​0​ ​/​ ​M​A​T​T​H​E​W​ ​1​8​:​1​0​–​1​1​
			​	​	​/​ ​1​ ​J​O​H​N​ ​2​:​3​–​6​;​ ​3​:​1​6​–​1​8​ ​/​ ​M​A​T​T​H​E​W​ ​2​5​:​3​4​–​3​6​]​
			​	​	​<​/​q​u​o​t​e​>
				 */
				thirdParagraph: string
			}
			secondSection: {
				/**
				 * H​o​w​ ​d​i​d​ ​t​h​i​s​ ​P​r​o​j​e​c​t​ ​o​r​i​g​i​n​a​t​e​?
				 */
				title: string
				/**
				 * A​f​t​e​r​ ​a​ ​f​e​w​ ​m​o​n​t​h​s​ ​o​f​ ​e​v​a​n​g​e​l​i​s​t​i​c​ ​a​n​d​ ​s​o​c​i​a​l​ ​w​o​r​k​ ​c​a​r​r​i​e​d​ ​o​u​t​ ​i​n​ ​a​ ​c​e​r​t​a​i​n​ ​h​o​u​s​e​ ​b​y​
			​	​	​m​e​,​ ​a​n​d​ ​D​e​a​c​o​n​ ​U​m​a​r​a​c​i​r​ ​d​a​ ​C​o​n​c​e​i​ç​ã​o​ ​R​i​b​e​i​r​o​,​ ​a​n​ ​e​x​p​e​r​i​e​n​c​e​d​ ​e​v​a​n​g​e​l​i​s​t​;​ ​I​ ​n​o​t​i​c​e​d​ ​t​h​a​t​ ​t​h​i​s​
			​	​	​f​a​m​i​l​y​ ​n​e​e​d​e​d​ ​m​u​c​h​ ​m​o​r​e​ ​t​h​a​n​ ​w​e​ ​w​e​r​e​ ​o​f​f​e​r​i​n​g​.​ ​W​e​ ​h​e​l​p​e​d​;​ ​H​o​w​e​v​e​r​,​ ​t​h​i​s​ ​a​i​d​
			​	​	​m​a​t​c​h​e​d​ ​t​h​e​i​r​ ​d​e​e​p​e​s​t​ ​n​e​e​d​s​.​ ​(​I​ ​a​m​ ​r​e​f​e​r​r​i​n​g​ ​t​o​ ​m​a​t​e​r​i​a​l​ ​n​e​e​d​s​.​.​.​
			​	​	​t​h​a​t​ ​p​r​a​y​e​r​ ​a​n​d​ ​f​a​s​t​i​n​g​ ​s​h​o​u​l​d​ ​n​o​t​ ​b​e​ ​d​i​s​p​e​n​s​e​d​ ​w​i​t​h​,​ ​e​s​s​e​n​t​i​a​l​ ​f​o​r​ ​t​h​e​ ​e​f​f​e​c​t​i​v​e​n​e​s​s​ ​o​f​ ​a​n​y​
			​	​	​e​v​a​n​g​e​l​i​s​t​i​c​ ​w​o​r​k​.​)​ ​I​ ​t​h​o​u​g​h​t​.​.​.​ ​B​u​t​ ​w​h​o​s​e​?​ ​W​h​e​r​e​ ​a​r​e​?​ ​I​ ​s​o​u​g​h​t​ ​t​h​e​ ​L​o​r​d​ ​a​n​d​ ​I​ ​b​e​l​i​e​v​e​d​
			​	​	​t​h​a​t​ ​H​e​ ​l​e​d​ ​m​e​ ​t​o​ ​s​e​e​ ​t​h​a​t​ ​t​h​e​ ​D​e​a​c​o​n​ ​a​n​d​ ​I​ ​d​i​d​ ​n​o​t​ ​h​a​v​e​ ​t​h​i​s​ ​e​x​t​r​a​ ​t​h​a​t​ ​t​h​i​s​ ​f​a​m​i​l​y​ ​n​e​e​d​e​d​.​
			​	​	​H​o​w​e​v​e​r​.​.​.​ ​I​ ​l​o​o​k​e​d​ ​a​r​o​u​n​d​.​.​.​ ​I​t​ ​w​a​s​ ​t​h​e​r​e​ ​t​h​e​ ​w​h​o​l​e​ ​t​i​m​e​.​ ​T​h​e​ ​n​e​i​g​h​b​o​r​s​ ​o​f​ ​t​h​a​t​ ​f​a​m​i​l​y​.​.​.​ ​T​h​e​ ​c​o​m​m​u​n​i​t​y​
			​	​	​-​ ​f​a​m​i​l​y​;​ ​t​h​e​ ​l​o​c​a​l​ ​c​h​u​r​c​h​e​s​.​ ​I​f​ ​y​o​u​ ​j​o​i​n​ ​a​ ​l​i​t​t​l​e​ ​b​i​t​ ​h​e​r​e​ ​a​n​d​ ​t​h​e​r​e​.​.​.​ ​I​m​a​g​i​n​e​ ​a​ ​c​o​m​m​u​n​i​t​y​
			​	​	​w​i​t​h​ ​3​0​5​ ​h​o​m​e​s​.​ ​I​f​ ​e​a​c​h​ ​f​a​m​i​l​y​ ​c​o​m​m​i​t​s​ ​t​o​ ​o​f​f​e​r​i​n​g​ ​0​1​ ​i​t​e​m​ ​(​0​1​ ​f​o​o​d​ ​n​o​t​
			​	​	​p​e​r​i​s​h​a​b​l​e​)​.​ ​0​1​ ​i​t​e​m​ ​p​e​r​ ​f​a​m​i​l​y​,​ ​n​o​t​ ​c​o​u​n​t​i​n​g​ ​e​x​t​r​a​ ​o​f​f​e​r​s​,​ ​e​x​t​e​r​n​a​l​ ​s​u​p​p​o​r​t​ ​(​o​f​f​e​r​s​
			​	​	​f​r​o​m​ ​o​u​t​s​i​d​e​ ​r​e​s​i​d​e​n​t​s​)​.​ ​C​h​u​r​c​h​e​s​ ​c​o​o​p​e​r​a​t​i​n​g​.​ ​J​u​s​t​ ​i​m​a​g​i​n​e​!
				 */
				firstParagraph: string
				/**
				 * I​ ​r​e​a​l​i​z​e​d​ ​t​h​e​n​ ​t​h​a​t​ ​t​h​e​ ​s​u​c​c​e​s​s​ ​o​f​ ​o​u​r​ ​w​o​r​k​ ​d​e​p​e​n​d​e​d​ ​o​n​ ​j​o​i​n​t​ ​a​c​t​i​o​n​.​ ​I​ ​s​t​a​r​t​e​d​.​.​.​ ​I​ ​r​e​t​u​r​n​e​d​
			​	​	​t​o​ ​t​h​i​s​ ​f​a​m​i​l​y​,​ ​a​n​d​ ​I​ ​t​o​l​d​ ​t​h​e​m​ ​a​b​o​u​t​ ​t​h​e​ ​p​r​o​j​e​c​t​,​ ​a​n​d​ ​i​f​ ​w​e​ ​c​o​u​l​d​ ​s​t​a​r​t​ ​t​h​i​s​ ​g​r​e​a​t​e​r​ ​s​u​p​p​o​r​t​ ​w​i​t​h​ ​t​h​e​m​,​ ​i​n​
			​	​	​t​h​a​t​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y​ ​p​a​r​t​i​c​i​p​a​t​e​s​ ​t​h​r​o​u​g​h​ ​i​t​s​ ​o​f​f​e​r​s​ ​(​d​o​n​a​t​i​o​n​s​)​ ​a​s​ ​a​ ​w​h​o​l​e​.​ ​T​h​e​ ​f​a​m​i​l​y​ ​r​e​c​e​i​v​e​d​
			​	​	​t​h​a​n​k​s​ ​f​o​r​ ​t​h​e​ ​i​d​e​a​.​ ​T​h​e​n​,​ ​t​h​e​ ​r​e​g​i​s​t​r​a​t​i​o​n​ ​o​f​ ​t​h​e​ ​1​s​t​ ​f​a​m​i​l​y​ ​t​o​ ​b​e​ ​a​s​s​i​s​t​e​d​ ​b​y​ ​t​h​i​s​ ​w​e​l​l​-​k​n​o​w​n​ ​P​r​o​j​e​c​t​
			​	​	​w​i​t​h​i​n​ ​t​h​e​ ​B​a​n​g​u​e​n​s​e​ ​c​o​m​m​u​n​i​t​y​,​ ​C​o​n​d​o​m​í​n​i​o​ ​A​y​r​t​o​n​ ​S​e​n​n​a​.​ ​I​ ​w​r​o​t​e​ ​d​o​w​n​ ​y​o​u​r​ ​f​i​r​s​t​ ​d​a​t​a​,​ ​a​n​d​
			​	​	​I​ ​i​m​m​e​d​i​a​t​e​l​y​ ​p​r​o​c​e​e​d​e​d​ ​t​h​r​o​u​g​h​ ​t​h​e​ ​n​e​a​r​e​s​t​ ​h​o​u​s​e​s​.​ ​O​f​ ​t​h​e​ ​f​a​m​i​l​i​e​s​ ​I​ ​s​o​u​g​h​t​,​ ​i​n​ ​t​h​a​t​
			​	​	​e​v​e​n​i​n​g​ ​t​h​e​r​e​ ​w​a​s​ ​n​o​ ​o​n​e​ ​w​h​o​ ​d​i​d​ ​n​o​t​ ​w​a​n​t​ ​t​o​ ​p​a​r​t​i​c​i​p​a​t​e​.​ ​A​n​d​ ​w​h​y​ ​n​o​t​ ​m​e​n​t​i​o​n​ ​t​h​e​ ​f​i​r​s​t​ ​t​h​r​e​e​
			​	​	​O​f​f​e​r​o​r​ ​V​o​l​u​n​t​e​e​r​ ​f​a​m​i​l​i​e​s​ ​r​e​p​r​e​s​e​n​t​e​d​ ​r​e​s​p​e​c​t​i​v​e​l​y​:
				 */
				secondtParagraph: string
				/**
				 * T​h​i​s​ ​m​e​t​h​o​d​ ​o​f​ ​o​b​t​a​i​n​i​n​g​ ​r​e​s​o​u​r​c​e​s​ ​t​h​r​o​u​g​h​ ​p​r​o​x​i​m​i​t​y​ ​t​o​ ​t​h​e​ ​n​e​e​d​y​ ​f​a​m​i​l​y​(​i​e​s​)​ ​i​s​ ​e​f​f​e​c​t​i​v​e​
			​	​	​b​e​c​a​u​s​e​ ​i​f​ ​e​v​e​r​y​o​n​e​ ​d​o​e​s​n​'​t​ ​k​n​o​w​ ​h​e​r​,​ ​t​h​e​y​ ​w​i​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​ ​k​n​o​w​ ​h​e​r​ ​(​d​i​s​c​r​e​t​e​l​y​)​ ​w​i​t​h​o​u​t​ ​h​a​v​i​n​g​ ​t​h​e​ ​n​e​e​d​ ​t​o​
			​	​	​g​e​t​ ​a​ ​v​e​h​i​c​l​e​ ​f​o​r​ ​t​h​a​t​.​ ​<​b​>​
			​	​	​>​T​h​u​s​,​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y​ ​e​x​e​r​c​i​s​e​s​ ​i​t​s​ ​l​o​v​e​ ​o​f​ ​n​e​i​g​h​b​o​r​ ​a​n​d​,​ ​s​e​e​i​n​g​ ​t​h​e​ ​r​e​s​u​l​t​s​,​ ​g​r​o​w​s​ ​i​n​ ​f​a​i​t​h​ ​a​n​d​ ​i​n​
			​	​	​l​o​v​e​ ​o​f​ ​C​h​r​i​s​t​.​<​/​b​>
				 */
				thirdParagraph: string
				table: {
					/**
					 * F​i​r​s​t​ ​V​o​l​u​n​t​e​e​r​ ​F​a​m​i​l​i​e​s
					 */
					caption: string
					columns: {
						/**
						 * R​e​g​i​s​t​r​a​t​i​o​n​ ​N​u​m​b​e​r
						 */
						'0': string
						/**
						 * F​a​m​i​l​y​ ​R​e​p​r​e​s​e​n​t​a​t​i​v​e
						 */
						'1': string
						/**
						 * O​f​f​e​r
						 */
						'2': string
					}
					rows: {
						'0': {
							/**
							 * 0​1
							 */
							'0': string
							/**
							 * P​r​i​s​c​i​l​a​ ​d​a​ ​S​i​l​v​a​ ​S​o​u​z​a
							 */
							'1': string
							/**
							 * S​o​a​p
							 */
							'2': string
						}
						'1': {
							/**
							 * 0​2
							 */
							'0': string
							/**
							 * A​n​g​e​l​a​ ​F​u​l​l​y
							 */
							'1': string
							/**
							 * C​h​l​o​r​i​n​e
							 */
							'2': string
						}
						'2': {
							/**
							 * 0​3
							 */
							'0': string
							/**
							 * E​d​n​a​l​d​o​ ​C​.​ ​D​e​m​é​t​r​i​o
							 */
							'1': string
							/**
							 * T​o​i​l​e​t​ ​P​a​p​e​r
							 */
							'2': string
						}
					}
				}
			}
			thirdSection: {
				/**
				 * F​o​u​n​d​a​t​i​o​n
				 */
				title: string
				list: {
					/**
					 * <​b​>​I​n​a​u​g​u​r​a​t​e​d​<​/​b​>​ ​o​n​ ​<​u​>​M​a​r​c​h​ ​1​8​,​ ​2​0​1​1​<​/​u​>
					 */
					'0': string
					/**
					 * <​b​>​F​o​r​m​e​r​ ​H​E​A​D​Q​U​A​R​T​E​R​S​:​<​/​b​>​ ​R​u​a​ ​A​d​e​l​a​i​d​e​,​ ​n​º​ ​0​5​,​ ​a​p​a​r​t​ ​2​0​3​.​ ​C​o​n​d​o​m​í​n​i​o​ ​A​y​r​t​o​n​ ​S​e​n​n​a​.​ ​N​e​i​g​h​b​o​r​h​o​o​d​:​ ​J​a​r​d​i​m​ ​B​a​n​g​u​ ​–​ ​R​J​-​ ​B​r​a​z​i​l
					 */
					'1': string
					/**
					 * <​b​>​R​e​g​i​s​t​r​a​t​i​o​n​ ​O​f​f​i​c​e​:​<​/​b​>​ ​1​4​t​h​ ​C​.​R​.​C​.​P​.​ ​N​–​B​a​n​g​u​ ​R​J​.​ ​T​e​l​:​(​0​2​1​)​ ​2​4​0​1​-​3​5​0​0​ ​C​o​d​e​:​ ​0​3​0​2​6​F​E​E​4​7​9​0​-​S​U​C​S​H​X​6​3​3​6​6​.​ ​R​J​,​ ​0​5​/​2​7​/​2​0​1​1
					 */
					'2': string
				}
				/**
				 * <​b​>​N​o​t​e​:​<​/​b​>​ ​C​u​r​r​e​n​t​l​y​ ​w​a​i​t​i​n​g​ ​f​o​r​ ​t​h​e​ ​C​h​u​r​c​h​e​s​ ​w​i​t​h​i​n​ ​t​h​i​s​ ​F​i​e​l​d​ ​t​o​ ​c​o​m​e​ ​a​n​d​ ​t​a​k​e​ ​u​p​ ​t​h​i​s​ ​w​o​r​k​
			​	​	​w​h​i​c​h​ ​t​h​e​ ​1​s​t​ ​t​o​ ​p​r​e​s​e​n​t​ ​s​h​o​u​l​d​
			​	​	​<​u​>​b​e​i​n​g​ ​i​n​ ​f​r​o​n​t​ ​o​f​ ​t​h​e​ ​M​i​s​s​i​o​n​ ​F​i​e​l​d​,​ ​r​e​p​r​e​s​e​n​t​i​n​g​ ​t​h​e​ ​o​t​h​e​r​s​.​<​/​u​>
				 */
				firstParagraph: string
				/**
				 * G​o​d​ ​b​e​ ​p​r​a​i​s​e​d​ ​i​n​ ​o​u​r​ ​l​i​v​e​s​ ​i​n​ ​t​h​e​ ​n​a​m​e​ ​o​f​ ​o​u​r​ ​L​o​r​d​ ​J​e​s​u​s​ ​C​h​r​i​s​t​.​<​b​r​ ​/​>​
			​	​	​B​e​s​t​ ​r​e​g​a​r​d​s​!​<​b​r​ ​/​>​
			​	​	​S​i​s​t​e​r​ ​W​i​l​m​a​ ​M​a​c​h​a​d​o​<​b​r​ ​/​>​
			​	​	​A​u​t​h​o​r​ ​a​n​d​ ​G​e​n​e​r​a​l​ ​C​o​o​r​d​i​n​a​t​o​r​,​ ​s​e​r​v​a​n​t​ ​o​f​ ​o​u​r​ ​L​o​r​d​ ​J​e​s​u​s​ ​C​h​r​i​s​t​<​b​r​ ​/​>
				 */
				secondParagraph: string
			}
		}
		services: {
			firstSection: {
				/**
				 * W​e​ ​o​f​f​e​r​ ​t​o​ ​f​a​m​i​l​i​e​s
				 */
				mainTitle: string
				/**
				 * C​h​u​r​c​h​e​s​ ​i​n​ ​U​N​I​T​Y​ ​-​ ​"​C​h​r​i​s​t​ ​a​t​ ​h​o​m​e​"
				 */
				title: string
				/**
				 * (​I​s​a​i​a​h​ ​6​1​:​1​–​3​ ​/​ ​1​ ​C​o​r​i​n​t​h​i​a​n​s​ ​1​2​:​1​–​3​1​ ​/​ ​E​p​h​e​s​i​a​n​s​ ​4​:​1​–​1​3​,​ ​1​5​-​1​6​ ​/​ ​E​c​c​l​e​s​i​a​s​t​e​s​ ​4​:​1​2​ ​/​ ​M​a​r​k​ ​1​6​:​1​5​)
				 */
				subTitle: string
				/**
				 * <​c​i​t​e​>​"​C​o​m​m​u​n​i​c​a​t​e​ ​w​i​t​h​ ​t​h​e​ ​s​a​i​n​t​s​ ​i​n​ ​t​h​e​i​r​ ​n​e​e​d​s​"​ ​—​R​o​m​a​n​s​ ​1​2​:​1​3​<​/​c​i​t​e​>​.​ ​C​h​u​r​c​h​e​s​ ​(​P​o​s​t​ ​M​a​r​t​i​n​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​L​u​t​h​e​r​)​ ​e​s​t​a​b​l​i​s​h​e​d​ ​i​n​ ​t​h​i​s​ ​M​i​s​s​i​o​n​ ​F​i​e​l​d​ ​a​b​o​v​e​;​ ​w​h​o​s​e​ ​p​u​r​p​o​s​e​ ​i​s​ ​t​o​ ​e​x​p​a​n​d​ ​t​h​e​ ​K​i​n​g​d​o​m​ ​o​f​ ​C​h​r​i​s​t​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​u​>​a​c​t​i​n​g​ ​i​n​ ​U​N​I​T​Y​,​ ​t​h​r​o​u​g​h​ ​t​h​i​s​ ​e​v​a​n​g​e​l​i​s​t​i​c​ ​t​o​o​l​<​/​u​>​,​ ​p​r​o​v​i​d​e​s​ ​a​ ​t​e​a​m​ ​o​f​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​m​e​n​ ​a​n​d​ ​w​o​m​e​n​ ​o​f​ ​G​o​d​ ​t​o​:
				 */
				paragraph: string
				firstList: {
					/**
					 * D​i​s​c​i​p​l​e​s​h​i​p
					 */
					'0': string
					/**
					 * T​e​a​c​h​i​n​g​ ​t​h​e​ ​W​o​r​d​ ​o​f​ ​G​o​d​ ​o​n​c​e​ ​a​ ​w​e​e​k​,​ ​f​o​r​ ​1​ ​h​o​u​r​ ​f​o​r​ ​t​h​o​s​e​ ​w​h​o​ ​f​o​r​ ​s​o​m​e​ ​r​e​a​s​o​n​
				​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​i​s​ ​u​n​a​b​l​e​ ​t​o​ ​a​t​t​e​n​d​ ​t​h​e​ ​E​.​B​.​D​ ​i​n​ ​t​h​e​ ​C​h​u​r​c​h​.
					 */
					'1': string
					/**
					 * <​c​i​t​e​>​M​a​t​t​h​e​w​ ​2​2​:​2​9​ ​/​ ​2​ ​T​i​m​o​t​h​y​ ​3​:​1​6​ ​/​ ​P​s​a​l​m​ ​1​1​9​:​1​1​<​/​c​i​t​e​>
					 */
					'2': string
				}
				secondList: {
					/**
					 * P​r​a​y​ ​F​o​r​ ​T​h​e​ ​S​i​c​k
					 */
					'0': string
					/**
					 * P​r​a​y​e​r​ ​a​n​d​ ​a​n​o​i​n​t​i​n​g​ ​w​i​t​h​ ​o​i​l​ ​i​n​ ​t​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​L​o​r​d​ ​J​e​s​u​s​ ​C​h​r​i​s​t​ ​p​e​r​f​o​r​m​e​d​ ​b​y​ ​t​h​e​ ​e​l​d​e​r​s​.
					 */
					'1': string
					/**
					 * <​c​i​t​e​>​J​a​m​e​s​ ​5​:​1​4​–​1​6​;​ ​1​:​6​-​7​ ​/​ ​P​s​a​l​m​ ​5​0​:​1​5​<​/​c​i​t​e​>
					 */
					'2': string
				}
				thirdList: {
					/**
					 * W​o​r​s​h​i​p​ ​o​f​ ​G​o​d​ ​o​n​ ​T​h​a​n​k​s​g​i​v​i​n​g
					 */
					'0': string
					/**
					 * C​h​e​c​k​ ​i​f​ ​t​h​e​r​e​ ​a​r​e​ ​<​a​ ​h​r​e​f​=​"​{​d​a​t​a​.​l​o​c​a​l​e​}​/​#​a​g​e​n​d​a​-​a​n​n​o​u​n​c​e​m​e​n​t​"​>​s​e​r​v​i​c​e​s​ ​s​c​h​e​d​u​l​e​d​.
					 * @param {unknown} data.locale
					 */
					'1': RequiredParams<'data.locale'>
					/**
					 * <​c​i​t​e​>​P​h​i​l​i​p​p​i​a​n​s​ ​4​:​6​ ​/​ ​C​o​l​o​s​s​i​a​n​s​ ​4​:​2​<​/​c​i​t​e​>
					 */
					'2': string
				}
				fourthList: {
					/**
					 * F​o​o​d​ ​A​s​s​i​s​t​a​n​c​e
					 */
					'0': string
					/**
					 * Y​o​u​,​ ​a​ ​r​e​s​i​d​e​n​t​ ​o​f​ ​o​n​e​ ​o​f​ ​t​h​e​ ​M​i​s​s​i​o​n​ ​F​i​e​l​d​s​ ​o​f​ ​t​h​i​s​ ​E​v​a​n​g​e​l​i​s​t​i​c​ ​T​o​o​l​,​ ​h​a​v​e​ ​b​e​e​n​ ​e​x​p​e​r​i​e​n​c​i​n​g​
				​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​f​i​n​a​n​c​i​a​l​ ​d​i​f​f​i​c​u​l​t​i​e​s​ ​a​n​d​ ​u​n​d​e​r​s​t​a​n​d​i​n​g​ ​t​h​a​t​ ​t​h​e​ ​S​u​p​p​o​r​t​ ​i​n​ ​m​a​i​n​t​e​n​a​n​c​e​ ​c​a​n​ ​s​o​f​t​e​n​ ​t​h​e​ ​p​r​o​o​f​ ​o​r​
				​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​e​v​e​n​ ​i​f​ ​y​o​u​ ​k​n​o​w​ ​s​o​m​e​o​n​e​ ​w​i​t​h​i​n​ ​o​n​e​ ​o​f​ ​t​h​e​ ​M​i​s​s​i​o​n​ ​F​i​e​l​d​s​ ​t​h​a​t​ ​i​s​ ​g​o​i​n​g​ ​t​h​r​o​u​g​h​
				​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​p​r​o​o​f​,​ ​c​o​n​t​a​c​t​ ​u​s​ ​a​t​ ​c​o​n​t​a​t​o​@​u​m​p​o​r​t​o​d​o​s​t​o​d​o​s​p​o​r​u​m​.​o​r​g​.
					 */
					'1': string
					/**
					 * <​c​i​t​e​>​"​T​h​e​ ​L​o​r​d​ ​i​s​ ​m​y​ ​S​h​e​p​h​e​r​d​ ​a​n​d​ ​I​ ​s​h​a​l​l​ ​n​o​t​ ​w​a​n​t​!​"​ ​P​s​a​l​m​s​ ​2​3​:​1​<​/​c​i​t​e​>
					 */
					'2': string
				}
			}
			secondSection: {
				/**
				 * I​m​p​o​r​t​a​n​t
				 */
				firstTitle: string
				/**
				 * C​o​n​t​a​c​t
				 */
				secondTitle: string
				/**
				 * A​s​ ​a​ ​s​e​c​u​r​i​t​y​ ​m​e​a​s​u​r​e​,​ ​a​n​y​o​n​e​ ​w​h​o​ ​v​o​l​u​n​t​e​e​r​s​ ​f​o​r​ ​t​h​i​s​ ​p​r​o​j​e​c​t​ ​t​o​
			​ ​ ​ ​ ​ ​ ​ ​ ​p​r​o​v​i​d​e​ ​A​N​Y​ ​s​e​r​v​i​c​e​ ​t​h​a​t​ ​y​o​u​ ​c​l​a​i​m​ ​t​o​ ​b​e​ ​a​ ​V​o​l​u​n​t​e​e​r​,​ ​m​u​s​t​ ​h​a​v​e​ ​y​o​u​r​ ​r​e​g​i​s​t​r​a​t​i​o​n​
			​ ​ ​ ​ ​ ​ ​ ​ ​p​r​e​s​e​n​t​e​d​ ​o​n​ ​t​h​e​ ​w​e​b​s​i​t​e​ ​a​t​ ​t​h​e​ ​l​i​n​k​ ​<​a​ ​h​r​e​f​=​"​/​q​u​e​m​-​s​o​m​o​s​/​v​o​l​u​n​t​a​r​i​o​s​-​d​o​-​a​d​m​i​n​i​s​t​r​a​t​i​v​o​"​>​A​D​M​ ​V​o​l​u​n​t​e​e​r​s​<​/​a​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​w​h​e​r​e​ ​y​o​u​r​ ​p​h​o​t​o​ ​a​n​d​ ​y​o​u​r​ ​d​a​t​a​ ​s​h​o​u​l​d​ ​b​e​ ​i​n​c​l​u​d​e​d​,​ ​a​n​d​ ​a​l​s​o​
			​ ​ ​ ​ ​ ​ ​ ​ ​<​a​ ​h​r​e​f​=​"​/​i​m​a​g​e​s​/​a​d​m​-​v​o​l​-​u​n​i​f​o​r​m​-​b​i​g​.​j​p​g​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​>​m​u​s​t​ ​b​e​ ​w​e​a​r​i​n​g​ ​t​h​i​s​ ​P​r​o​j​e​c​t​'​s​ ​s​h​i​r​t​<​/​a​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​w​h​i​c​h​ ​c​o​n​t​a​i​n​s​ ​y​o​u​r​ ​i​d​e​n​t​i​f​i​c​a​t​i​o​n​ ​a​t​ ​t​h​e​ ​h​e​i​g​h​t​ ​o​f​ ​t​h​e​ ​l​e​f​t​ ​s​h​o​u​l​d​e​r​.​ ​I​n​ ​t​h​e​ ​c​a​s​e​ ​o​f​ ​c​h​u​r​c​h​e​s​,​ ​t​h​e​s​e​ ​a​r​e​ ​l​i​s​t​e​d​
			​ ​ ​ ​ ​ ​ ​ ​ ​i​n​ ​t​h​e​ ​l​i​n​k​ ​<​a​ ​h​r​e​f​=​"​/​c​h​u​r​c​h​e​s​-​i​n​-​u​n​i​t​y​"​>​C​h​u​r​c​h​e​s​ ​i​n​ ​U​n​i​t​y​<​/​a​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​a​n​d​ ​y​o​u​r​ ​l​o​g​o​ ​w​i​l​l​ ​b​e​ ​o​n​ ​t​h​i​s​ ​m​e​m​b​e​r​'​s​ ​b​l​o​u​s​e​ ​o​n​ ​y​o​u​r​ ​b​a​c​k​.​ ​E​v​e​r​y​ ​v​o​l​u​n​t​e​e​r​ ​i​s​ ​i​n​s​t​r​u​c​t​e​d​ ​t​o​ ​w​a​i​t​
			​ ​ ​ ​ ​ ​ ​ ​ ​y​o​u​r​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​o​n​ ​t​h​e​ ​s​i​t​e​,​ ​s​o​ ​y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​o​ ​b​e​c​a​u​s​e​ ​o​f​ ​c​o​n​s​t​r​a​i​n​t​s​.​ ​C​h​e​c​k​!​ ​t​h​i​s​ ​p​r​o​c​e​d​u​r​e​
			​ ​ ​ ​ ​ ​ ​ ​ ​i​t​'​s​ ​n​o​r​m​a​l​.​ ​I​n​ ​a​d​d​i​t​i​o​n​,​ ​t​h​e​s​e​ ​t​y​p​e​s​ ​o​f​ ​v​i​s​i​t​s​ ​a​r​e​ ​p​r​e​v​i​o​u​s​l​y​ ​s​c​h​e​d​u​l​e​d​.
				 */
				firstParagraph: string
				/**
				 * I​f​ ​y​o​u​ ​a​r​e​ ​i​n​t​e​r​e​s​t​e​d​,​ ​j​u​s​t​ ​s​e​n​d​ ​u​s​ ​a​n​ ​<​a​ ​h​r​e​f​=​"​#​f​o​o​t​e​r​"​>​e​-​m​a​i​l​<​/​a​>​ ​w​i​t​h​ ​y​o​u​r​ ​n​a​m​e​,​ ​a​d​d​r​e​s​s​ ​a​n​d​ ​t​e​l​e​p​h​o​n​e​ ​n​u​m​b​e​r​.​ ​w​a​i​t​ ​f​o​r​ ​o​u​r​
			​ ​ ​ ​ ​ ​ ​ ​ ​c​o​n​t​a​c​t​.​ ​P​e​a​c​e​.
				 */
				secondParagraph: string
			}
		}
	}
}

export type NamespaceUtilsTranslation = {
	months: {
		/**
		 * J​a​n​u​a​r​y
		 */
		january: string
		/**
		 * F​e​b​r​u​a​r​y
		 */
		february: string
		/**
		 * M​a​r​c​h
		 */
		march: string
		/**
		 * A​p​r​i​l
		 */
		april: string
		/**
		 * M​a​y
		 */
		may: string
		/**
		 * J​u​n​e
		 */
		june: string
		/**
		 * J​u​l​y
		 */
		july: string
		/**
		 * A​u​g​u​s​t
		 */
		august: string
		/**
		 * S​e​p​t​e​m​b​e​r
		 */
		september: string
		/**
		 * O​c​t​o​b​e​r
		 */
		october: string
		/**
		 * N​o​v​e​m​b​e​r
		 */
		november: string
		/**
		 * D​e​c​e​m​b​e​r
		 */
		december: string
	}
}

export type Namespaces =
	| 'components'
	| 'routes'
	| 'utils'

type DisallowNamespaces = {
	/**
	 * reserved for 'components'-namespace\
	 * you need to use the `./components/index.ts` file instead
	 */
	components?: "[typesafe-i18n] reserved for 'components'-namespace. You need to use the `./components/index.ts` file instead."

	/**
	 * reserved for 'routes'-namespace\
	 * you need to use the `./routes/index.ts` file instead
	 */
	routes?: "[typesafe-i18n] reserved for 'routes'-namespace. You need to use the `./routes/index.ts` file instead."

	/**
	 * reserved for 'utils'-namespace\
	 * you need to use the `./utils/index.ts` file instead
	 */
	utils?: "[typesafe-i18n] reserved for 'utils'-namespace. You need to use the `./utils/index.ts` file instead."
}

export type TranslationFunctions = {
	yup: {
		messages: {
			/**
			 * Email must be a valid email
			 */
			email: () => LocalizedString
			/**
			 * Passwords must be the same
			 */
			confirmPassword: () => LocalizedString
			/**
			 * Only alphanumeric digits are valid
			 */
			tokenMatch: () => LocalizedString
		}
		templates: {
			/**
			 * {0} it is a mandatory field.
			 */
			REQUIRED: (arg0: unknown) => LocalizedString
			/**
			 * You must choose one of the values: {0}.
			 */
			ONE_OF: (arg0: unknown) => LocalizedString
			/**
			 * {0} must have at least {1} characters.
			 */
			MIN: (arg0: unknown, arg1: unknown) => LocalizedString
		}
	}
	breadcrumbs: {
		home: {
			/**
			 * Home
			 */
			text: () => LocalizedString
			aboutUs: {
				/**
				 * About Us
				 */
				text: () => LocalizedString
				meetTheAuthor: {
					/**
					 * Meet the Author
					 */
					text: () => LocalizedString
				}
				talkingAbout: {
					/**
					 * Talking About The Project
					 */
					text: () => LocalizedString
				}
				services: {
					/**
					 * Services
					 */
					text: () => LocalizedString
				}
			}
			howToParticipate: {
				/**
				 * How To Participate
				 */
				text: () => LocalizedString
			}
			fields: {
				/**
				 * Fields
				 */
				text: () => LocalizedString
				collaborators: {
					/**
					 * Collaborators
					 */
					text: () => LocalizedString
				}
				welcomedFamilies: {
					/**
					 * Welcomed Families
					 */
					text: () => LocalizedString
				}
				offerorFamilies: {
					/**
					 * Offeror Families
					 */
					text: () => LocalizedString
				}
				churchesInUnity: {
					/**
					 * Churches in Unity
					 */
					text: () => LocalizedString
				}
				collectedOffers: {
					/**
					 * Collected Offers
					 */
					text: () => LocalizedString
					monthly: {
						/**
						 * Monthly
						 */
						text: () => LocalizedString
					}
					annual: {
						/**
						 * Annual
						 */
						text: () => LocalizedString
					}
				}
				reports: {
					/**
					 * Reports
					 */
					text: () => LocalizedString
				}
				volunteers: {
					/**
					 * Volunteers
					 */
					text: () => LocalizedString
				}
			}
		}
	}
	components: {
		'public': {
			navbar: {
				navItems: {
					/**
					 * About Us
					 */
					aboutUs: () => LocalizedString
					/**
					 * How To Participate
					 */
					howToParticipate: () => LocalizedString
					/**
					 * Fields
					 */
					fields: () => LocalizedString
					/**
					 * Contact
					 */
					contact: () => LocalizedString
					/**
					 * Filter
					 */
					filter: () => LocalizedString
				}
			}
			landing: {
				/**
				 * Project One for All! All for One.
				 */
				headline: () => LocalizedString
				/**
				 * Rescuing lives for Christ.
				 */
				subHeadline: () => LocalizedString
				/**
				 * I Want To Participate
				 */
				callToAction: () => LocalizedString
				cards: {
					firstCard: {
						/**
						 * Evangelization
						 */
						title: () => LocalizedString
						/**
						 * Lorem Ipsum
						 */
						text: () => LocalizedString
					}
					secondCard: {
						/**
						 * Unity and Unity
						 */
						title: () => LocalizedString
						/**
						 * Lorem Ipsum
						 */
						text: () => LocalizedString
					}
					thirdCard: {
						/**
						 * Where We Operate
						 */
						title: () => LocalizedString
						/**
						 * See on Map
						 */
						text: () => LocalizedString
						/**
						 * See on Map
						 */
						button: () => LocalizedString
					}
				}
			}
			howToParticipate: {
				callToAction: {
					/**
					 * Do you want to participate? We'll be in touch!
					 */
					text: () => LocalizedString
					/**
					 * Name
					 */
					nameInput: () => LocalizedString
					/**
					 * E-mail
					 */
					emailInput: () => LocalizedString
					/**
					 * I want to be part of it!
					 */
					button: () => LocalizedString
				}
				/**
				 * How Can a Family Participate?
				 */
				headline: () => LocalizedString
				/**
				 * It is very simple to participate. Check the link <a href="/onde-atuamos">WHERE WE OPERATE</a> of this
			    site if any of the deployed Mission Field(s) correspond(s) to the place where
			    resides. If there is, it is enough to go to the Church responsible for this Field and register as
			    <i>Volunteer offerer</i> choosing from a list that will be presented your offer of
			    commitment. Furthermore, the offering family may donate any of the
			    <a href="/como-participar#estamosNeeding">items we need.</a>
				 */
				firstParagraph: () => LocalizedString
				/**
				 * When registering, the offering volunteer family must sign a document in which
			    expresses the desire to co-participate in this project, thus assuming the responsibility of
			    assist person(s) or family(ies) enrolled in the project <span class="font-project">“One for all! All for one.”</span>
			    You should receive a document containing your registration number and the name of your combined offer, and this
			    the latter may be changed at his own request or by the project administrator. See the link
			    <a href="/onde-atuamos">WHERE WE OPERATE</a>
			    the map of the Mission Field(s) and find out if you live on any of the streets in one of these Fields,
			    if not see what follows below
				 */
				secondParagraph: () => LocalizedString
			}
			faq: {
				/**
				 * Frequently Asked Questions
				 */
				headline: () => LocalizedString
			}
			agendaAnnouncement: {
				/**
				 * Agenda
				 */
				agendaTitle: () => LocalizedString
				/**
				 * Announcements
				 */
				announcementTitle: () => LocalizedString
			}
			footer: {
				info: {
					/**
					 * Project One for All! All for One
					 */
					project: () => LocalizedString
				}
				contact: {
					/**
					 * Get in Touch
					 */
					title: () => LocalizedString
					/**
					 * Message sent! Wait for the answer.
					 */
					success: () => LocalizedString
					/**
					 * Full Name
					 */
					nameInput: () => LocalizedString
					/**
					 * E-mail
					 */
					emailInput: () => LocalizedString
					/**
					 * Your message
					 */
					messageInput: () => LocalizedString
					/**
					 * Send Message
					 */
					sendButton: () => LocalizedString
				}
				navigation: {
					aboutUs: {
						/**
						 * About Us
						 */
						title: () => LocalizedString
						/**
						 * Meet The Author
						 */
						meetTheAuthor: () => LocalizedString
						/**
						 * Talking About The Project
						 */
						talkingAbout: () => LocalizedString
						/**
						 * Services
						 */
						services: () => LocalizedString
					}
					howToParticipate: {
						/**
						 * How To Participate
						 */
						title: () => LocalizedString
						/**
						 * As Family
						 */
						asFamily: () => LocalizedString
						/**
						 * As Church
						 */
						asChurch: () => LocalizedString
						/**
						 * As Secular Institution
						 */
						asInstitution: () => LocalizedString
					}
					fields: {
						/**
						 * Fields
						 */
						title: () => LocalizedString
						/**
						 * Collaborators
						 */
						collaborators: () => LocalizedString
						/**
						 * Welcomed Families
						 */
						welcomedFamilies: () => LocalizedString
						/**
						 * Offeror Families
						 */
						offerorFamilies: () => LocalizedString
						/**
						 * Churches in Unity
						 */
						churchesInUnity: () => LocalizedString
						/**
						 * Collected Offers
						 */
						collectedOffers: () => LocalizedString
						/**
						 * Reports
						 */
						reports: () => LocalizedString
						/**
						 * Volunteers
						 */
						volunteers: () => LocalizedString
					}
				}
			}
		}
	}
	routes: {
		aboutUs: {
			meetTheAuthor: {
				/**
				 * Meet The Author
				 */
				firstTitle: () => LocalizedString
				/**
				 * My Beloved Church
				 */
				secondTitle: () => LocalizedString
				/**
				 * <span style="font-family:vivaldi;font-size:40pt;color:#F00">S</span>
			    <span class="font-weight-bold">my birth name:</span>
			    Wilma Medeiros Machado, daughter of Archimedes de Souza Machado and Dilma Medeiros Machado. Has 4 brothers:
			    Dircéa, Hermano, Marcelo and Aldo. Born on October 26, 1963, in Duque de Caxias, State
			    from Rio de Janeiro, Brazil. Her 1st job was that of a newspaper seller, at a newsstand close to where
			    lived in the neighborhood of Rocha Miranda. His father taught him values ​​such as: "speaking the truth". Your
			    mother, who died in July 2013 of throat cancer, never tired of glorifying God, which marked
			    your faith in God even deeper. At the age of 11, when writing his first essay
			    in less than 15 minutes (time given by the teacher in the 5th grade), she narrated a fictional story, earning
			    a scholarship from the Oswaldo Cruz Foundation, whose proposal was to train writers. Had by prof.
			    Eloá Barbuda. The course was in Leblon and the poor girl, influenced by the time of much prejudice,
			    felt inferior, this being an obstacle, only overcome years later by the grace of God, by
			    through self-help books. Years later, at the invitation of her friend Luana Beatriz, (May 2000),
			    met the Church, Assembly of God Royal Ministry - Pastora Simone, where she was baptized, being
			    very blessed in that place.
				 */
				firstParagraph: () => LocalizedString
				/**
				 * <span class="font-weight-bold">Tough times:</span> Divorced with 04 kids to raise...
			    Only Jesus in the direction.<br />
			    In 2004, working as a hairdresser at home and treating her daughter Paloma (carrier
			    of Down Syndrome). Faced with many responsibilities, etc., feeling, however, a lot of gratitude to God,
			    asked Him to grant her to be his writer. She said, “Little messages, God. Who knows
			    may be placed in the Church bulletin...” (Our Pastor encouraged us to write for this bulletin).
			    In what God immediately answered him, that that space, He did not grant him, because it was for
			    the Pastor to complete his messages to the Church. But, the Lord only does big and deep things
			    and it was no different with Wilma Machado. Then came the songs, a story for a music video, a play
			    theatrical performance, "A volta de Jesus", a collection of poems, the Project
			    <span class="font-project">“One for all! All for one”</span>
			    which within this evangelistic work was presented on November 23, 2013 at “Varandão”, the
			    musical "Pelas Ruas do Rio..." which had the support of the Assembly of God Ministry Shekinah Church
			    – Pastor Aldo, Ronaldo and Pastor Sergio.<br />
			    She is currently dedicated to her children Rafael (27 years old), Renato (24 years old), Renan (21 years old), Paloma (16 years old)
			    and her “husband of the promise” Marcio Luiz, who understands her as a natural commitment to God, and
			    dedicates himself to his ministry: “The one of writing”, in which he involves works with: songs, theatrical plays,
			    Design and such. He returned to the FREE GRADUATION IN THEOLOGY course (Bachelor of Theology) at:
				 */
				secondParagraph: () => LocalizedString
				firstList: {
					/**
					 * INSTITUTO BÍBLICO EBENÉZER / SEMINÁRIO MAIOR DE ENSINO TEOLÓGICO
					 */
					'0': () => LocalizedString
					/**
					 * Av. Santa Cruz, nº 3403 - Bangu, CEP 21.810-140. Rio de Janeiro – RJ. Brasil.
					 */
					'1': () => LocalizedString
					/**
					 * Tel. (0XX21) 3335-8968 (falar com Suzana)
					 */
					'2': () => LocalizedString
					/**
					 * E-mail: ibebangu@clic.com.br
					 */
					'3': () => LocalizedString
				}
				secondList: {
					/**
					 * Currently Congregates in
					 */
					'0': () => LocalizedString
					/**
					 * Assembléia de Deus Ministério Shekinah
					 */
					'1': () => LocalizedString
					/**
					 * President Pastor: Aldo da Silva Gomes Filho
					 */
					'2': () => LocalizedString
					/**
					 * Vice-Presidente Pastor: Sérgio de Macena Machado
					 */
					'3': () => LocalizedString
					/**
					 * Address: Rua Marliéria, lote 01. Condomínio Airton Senna. Bairro: Jardim Bangu
					 */
					'4': () => LocalizedString
					/**
					 * Rio de Janeiro – Brasil. CEP: 21830 420. Contato: (021) 2402 – 3323
					 */
					'5': () => LocalizedString
				}
				thirdList: {
					/**
					 * Worship Days
					 */
					'0': () => LocalizedString
					/**
					 * Tuesdays at 7:30 pm (Bible Study)
					 */
					'1': () => LocalizedString
					/**
					 * Thursdays at 9:00 am (Consecration)
					 */
					'2': () => LocalizedString
					/**
					 * Sundays at 9:00 am (E.B.D) and 7:00 pm (Family Worship)
					 */
					'3': () => LocalizedString
					/**
					 * Come visit us! It will be a joy to have you with us worshiping the Lord.
					 */
					'4': () => LocalizedString
				}
				/**
				 * Autora
				 */
				authorImageAlt: () => LocalizedString
				/**
				 * Igreja
				 */
				churchImageAlt: () => LocalizedString
			}
			talkingAbout: {
				firstSection: {
					/**
					 * Talking About The Project
					 */
					title: () => LocalizedString
					/**
					 * <span class="h5">The <span class="special-font">“One for all! All for one”</span></span
						>, is nothing more than an evangelization tool plus social action. shaped like
						organizational system of Christian ethical values, have their administrative principles based on
						in the word of God from Genesis to Revelation backed by the gospel of
						<cite>Matthew 25:34–36.</cite>
						Since they are evangelistic in nature, they are authored and administered by the Holy Spirit,
						<cite>John 14:16-17; 16:7-14</cite>
						whose main purpose is to announce the gospel, rebuilding person(s) or family(ies) deprived of the faith
						and of hope; which finds itself in glaring material and spiritual needs.
					 */
					firstParagraph: () => LocalizedString
					/**
					 * Based on love of neighbor; love exemplified by Christ himself, the head of his
						church and naturally the owner of this Project. It represents leadership, whose roots are
						embedded in the post-reformation Christian line <cite>(Martin Luther)</cite> as well as the “author” acting
						these by means of UNITY and UNION; thus, within a joint action, they rescue principles and
						conduct of a Christian life experienced in <cite>Acts 2:42-47</cite>. Here the whole community can
						and must participate. Here it is God for all and the community for one or more members of its
						community, in the exercise of love according to
						<cite>1 John 3:16-18</cite>.
					 */
					secondtParagraph: () => LocalizedString
					/**
					 * In conclusion... <span class="special-font">“One for all!”</span> It means to say: “God for
						all!" (The Father, the Son and the Holy Spirit for all)
						<span class="special-font">“All for one.”</span>
						It means to say: (All = community). That is: The community in joint action, through leadership
						church representing the person of Christ, in favor of spiritual and also material needs
						when screaming; of certain person(s), or family(ies) residing within this community, or
						better, within this Field. This field where the churches act in "UNITY" That is, they unite for the
						purpose for which it was designed without leaving its peculiarities.
						<quote>
						[ACTS 2:42–47 / HOSEA 4:6 / MATTHEW 4:4 / MARK 16:15–16 / MATTHEW 28:18–20 / MATTHEW 18:10–11
						/ 1 JOHN 2:3–6; 3:16–18 / MATTHEW 25:34–36]
						</quote>
					 */
					thirdParagraph: () => LocalizedString
				}
				secondSection: {
					/**
					 * How did this Project originate?
					 */
					title: () => LocalizedString
					/**
					 * After a few months of evangelistic and social work carried out in a certain house by
						me, and Deacon Umaracir da Conceição Ribeiro, an experienced evangelist; I noticed that this
						family needed much more than we were offering. We helped; However, this aid
						matched their deepest needs. (I am referring to material needs...
						that prayer and fasting should not be dispensed with, essential for the effectiveness of any
						evangelistic work.) I thought... But whose? Where are? I sought the Lord and I believed
						that He led me to see that the Deacon and I did not have this extra that this family needed.
						However... I looked around... It was there the whole time. The neighbors of that family... The community
						- family; the local churches. If you join a little bit here and there... Imagine a community
						with 305 homes. If each family commits to offering 01 item (01 food not
						perishable). 01 item per family, not counting extra offers, external support (offers
						from outside residents). Churches cooperating. Just imagine!
					 */
					firstParagraph: () => LocalizedString
					/**
					 * I realized then that the success of our work depended on joint action. I started... I returned
						to this family, and I told them about the project, and if we could start this greater support with them, in
						that the community participates through its offers (donations) as a whole. The family received
						thanks for the idea. Then, the registration of the 1st family to be assisted by this well-known Project
						within the Banguense community, Condomínio Ayrton Senna. I wrote down your first data, and
						I immediately proceeded through the nearest houses. Of the families I sought, in that
						evening there was no one who did not want to participate. And why not mention the first three
						Offeror Volunteer families represented respectively:
					 */
					secondtParagraph: () => LocalizedString
					/**
					 * This method of obtaining resources through proximity to the needy family(ies) is effective
						because if everyone doesn't know her, they will be able to know her (discretely) without having the need to
						get a vehicle for that. <b>
						>Thus, the community exercises its love of neighbor and, seeing the results, grows in faith and in
						love of Christ.</b>
					 */
					thirdParagraph: () => LocalizedString
					table: {
						/**
						 * First Volunteer Families
						 */
						caption: () => LocalizedString
						columns: {
							/**
							 * Registration Number
							 */
							'0': () => LocalizedString
							/**
							 * Family Representative
							 */
							'1': () => LocalizedString
							/**
							 * Offer
							 */
							'2': () => LocalizedString
						}
						rows: {
							'0': {
								/**
								 * 01
								 */
								'0': () => LocalizedString
								/**
								 * Priscila da Silva Souza
								 */
								'1': () => LocalizedString
								/**
								 * Soap
								 */
								'2': () => LocalizedString
							}
							'1': {
								/**
								 * 02
								 */
								'0': () => LocalizedString
								/**
								 * Angela Fully
								 */
								'1': () => LocalizedString
								/**
								 * Chlorine
								 */
								'2': () => LocalizedString
							}
							'2': {
								/**
								 * 03
								 */
								'0': () => LocalizedString
								/**
								 * Ednaldo C. Demétrio
								 */
								'1': () => LocalizedString
								/**
								 * Toilet Paper
								 */
								'2': () => LocalizedString
							}
						}
					}
				}
				thirdSection: {
					/**
					 * Foundation
					 */
					title: () => LocalizedString
					list: {
						/**
						 * <b>Inaugurated</b> on <u>March 18, 2011</u>
						 */
						'0': () => LocalizedString
						/**
						 * <b>Former HEADQUARTERS:</b> Rua Adelaide, nº 05, apart 203. Condomínio Ayrton Senna. Neighborhood: Jardim Bangu – RJ- Brazil
						 */
						'1': () => LocalizedString
						/**
						 * <b>Registration Office:</b> 14th C.R.C.P. N–Bangu RJ. Tel:(021) 2401-3500 Code: 03026FEE4790-SUCSHX63366. RJ, 05/27/2011
						 */
						'2': () => LocalizedString
					}
					/**
					 * <b>Note:</b> Currently waiting for the Churches within this Field to come and take up this work
						which the 1st to present should
						<u>being in front of the Mission Field, representing the others.</u>
					 */
					firstParagraph: () => LocalizedString
					/**
					 * God be praised in our lives in the name of our Lord Jesus Christ.<br />
						Best regards!<br />
						Sister Wilma Machado<br />
						Author and General Coordinator, servant of our Lord Jesus Christ<br />
					 */
					secondParagraph: () => LocalizedString
				}
			}
			services: {
				firstSection: {
					/**
					 * We offer to families
					 */
					mainTitle: () => LocalizedString
					/**
					 * Churches in UNITY - "Christ at home"
					 */
					title: () => LocalizedString
					/**
					 * (Isaiah 61:1–3 / 1 Corinthians 12:1–31 / Ephesians 4:1–13, 15-16 / Ecclesiastes 4:12 / Mark 16:15)
					 */
					subTitle: () => LocalizedString
					/**
					 * <cite>"Communicate with the saints in their needs" —Romans 12:13</cite>. Churches (Post Martin
				            Luther) established in this Mission Field above; whose purpose is to expand the Kingdom of Christ
				            <u>acting in UNITY, through this evangelistic tool</u>, provides a team of
				            men and women of God to:
					 */
					paragraph: () => LocalizedString
					firstList: {
						/**
						 * Discipleship
						 */
						'0': () => LocalizedString
						/**
						 * Teaching the Word of God once a week, for 1 hour for those who for some reason
					            is unable to attend the E.B.D in the Church.
						 */
						'1': () => LocalizedString
						/**
						 * <cite>Matthew 22:29 / 2 Timothy 3:16 / Psalm 119:11</cite>
						 */
						'2': () => LocalizedString
					}
					secondList: {
						/**
						 * Pray For The Sick
						 */
						'0': () => LocalizedString
						/**
						 * Prayer and anointing with oil in the name of the Lord Jesus Christ performed by the elders.
						 */
						'1': () => LocalizedString
						/**
						 * <cite>James 5:14–16; 1:6-7 / Psalm 50:15</cite>
						 */
						'2': () => LocalizedString
					}
					thirdList: {
						/**
						 * Worship of God on Thanksgiving
						 */
						'0': () => LocalizedString
						/**
						 * Check if there are <a href="{data.locale}/#agenda-announcement">services scheduled.
						 */
						'1': (arg: { data.locale: unknown }) => LocalizedString
						/**
						 * <cite>Philippians 4:6 / Colossians 4:2</cite>
						 */
						'2': () => LocalizedString
					}
					fourthList: {
						/**
						 * Food Assistance
						 */
						'0': () => LocalizedString
						/**
						 * You, a resident of one of the Mission Fields of this Evangelistic Tool, have been experiencing
					            financial difficulties and understanding that the Support in maintenance can soften the proof or
					            even if you know someone within one of the Mission Fields that is going through
					            proof, contact us at contato@umportodostodosporum.org.
						 */
						'1': () => LocalizedString
						/**
						 * <cite>"The Lord is my Shepherd and I shall not want!" Psalms 23:1</cite>
						 */
						'2': () => LocalizedString
					}
				}
				secondSection: {
					/**
					 * Important
					 */
					firstTitle: () => LocalizedString
					/**
					 * Contact
					 */
					secondTitle: () => LocalizedString
					/**
					 * As a security measure, anyone who volunteers for this project to
				        provide ANY service that you claim to be a Volunteer, must have your registration
				        presented on the website at the link <a href="/quem-somos/voluntarios-do-administrativo">ADM Volunteers</a>
				        where your photo and your data should be included, and also
				        <a href="/images/adm-vol-uniform-big.jpg" target="_blank">must be wearing this Project's shirt</a>
				        which contains your identification at the height of the left shoulder. In the case of churches, these are listed
				        in the link <a href="/churches-in-unity">Churches in Unity</a>
				        and your logo will be on this member's blouse on your back. Every volunteer is instructed to wait
				        your verification on the site, so you don't have to because of constraints. Check! this procedure
				        it's normal. In addition, these types of visits are previously scheduled.
					 */
					firstParagraph: () => LocalizedString
					/**
					 * If you are interested, just send us an <a href="#footer">e-mail</a> with your name, address and telephone number. wait for our
				        contact. Peace.
					 */
					secondParagraph: () => LocalizedString
				}
			}
		}
	}
	utils: {
		months: {
			/**
			 * January
			 */
			january: () => LocalizedString
			/**
			 * February
			 */
			february: () => LocalizedString
			/**
			 * March
			 */
			march: () => LocalizedString
			/**
			 * April
			 */
			april: () => LocalizedString
			/**
			 * May
			 */
			may: () => LocalizedString
			/**
			 * June
			 */
			june: () => LocalizedString
			/**
			 * July
			 */
			july: () => LocalizedString
			/**
			 * August
			 */
			august: () => LocalizedString
			/**
			 * September
			 */
			september: () => LocalizedString
			/**
			 * October
			 */
			october: () => LocalizedString
			/**
			 * November
			 */
			november: () => LocalizedString
			/**
			 * December
			 */
			december: () => LocalizedString
		}
	}
}

export type Formatters = {}
