// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import en from './en'
import pt_BR from './pt-BR'

import en_components from './en/components'
import en_routes from './en/routes'
import pt_BR_components from './pt-BR/components'
import pt_BR_routes from './pt-BR/routes'

const localeTranslations = {
	en: {
		...en,
		components: en_components,
		routes: en_routes
	},
	'pt-BR': {
		...pt_BR,
		components: pt_BR_components,
		routes: pt_BR_routes
	},
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
